#!/bin/sh

export PATH=/usr/local/bin:$PATH

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

npx pretty-quick --staged
npm run ea:prettier

if [ $? -eq 0 ]
then
  echo ""
  echo "${GREEN}✔ Prettier Auto-commit complete ${NC}"
  echo ""
else
  echo ""
  echo "${RED}! Prettier did not run successfully ${NC}"
  echo ""
  exit 1
fi

npm run xml:lint
if [ $? -eq 0 ]
then
  echo ""
  echo "${GREEN}✔ XML Linting complete ${NC}"
  echo ""
else
  echo ""
  echo "${RED}! XML Linting did not run successfully ${NC}"
  echo ""
  exit 1
fi

