#!/bin/sh

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

npx pretty-quick --staged
npm run ea:prettier

if [ $? -eq 0 ]
then
  echo ""
  echo "${GREEN}✔ Prettier Auto-commit complete ${NC}"
  echo ""
else
  echo ""
  echo "${RED}! Prettier did not run successfully ${NC}"
  echo ""
  exit 1
fi

folders=$( ls )
if [[ $folders == *"salesforce-scripts"* ]];then
  echo ""
  echo "${RED}! You need to delete the salesforce-scripts folder, as it is a submodule and will break the pipelines${NC}"
  echo ""
  exit 1
fi

exit 0
