substitutions:
  # git tag prefix for production deployments.
  _GIT_TAG_PREFIX: 'prod-'

options:
  workerPool: 'anz-cx-cloudbuild-dev-5ef683/custom-workers-dev-pool'

steps:
- id: 'Code Quality (PMD)'
  waitFor: [ '-' ]
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'run',  '-v', '/workspace:/workdir', 'hub.artifactory.gcp.anz/jamesmoriarty/pmd:6.18.0',
    'pmd',
      '-R', 'rulesets/apex/quickstart.xml',
      '-d', '.',
      '-l', 'apex',
      '-f', 'textcolor'
  ]

- id: git_init
  name: 'gcr.io/cloud-builders/git'
  waitFor: ['-']
  entrypoint: bash
  args:
  - -c
  - |
    # Tags are required by scripts/cicd.sh
    git fetch --tags
    # Ensure git authentication succeeds when pushing tags.
    ACTIVE_ACCOUNT=$$(gcloud auth list --filter=status:ACTIVE --format='value(account)')
    git config user.email "$$ACTIVE_ACCOUNT"
    git config user.name "GCP Cloud Build"

- id: 'Curl Salesforce'
  name: 'gcr.io/cloud-builders/curl'
  args:
  - -v
  - https://anz.my.salesforce.com/

- id: 'Decrypt the SFDX Key Using gcloud KMS'
  name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=keys/sfdx-auth-url-production.encrypted.txt
  - --plaintext-file=keys/sfdx-auth-url-production.txt
  - --location=global
  # TODO the keyring and key are not updated for the production environment.
  - --keyring=cloudbuild-keyring
  - --key=salesforce-prod-authentication-key

- id: 'Deploy to production'
  name: 'anzx-docker.artifactory.gcp.anz/salesforce/salesforce-builder:new'
  entrypoint: bash
  args:
  - -c
  - |
    # The value of USERNAME does not matter, as long as the alias is aligned between the deploy
    # command and the sfdx credential store.
    USERNAME='ASDF'
    sfdx force:auth:sfdxurl:store --sfdxurlfile 'keys/sfdx-auth-url-production.txt' --setalias "$$USERNAME" --json
    exec /workspace/scripts/cicd.sh --branch '${BRANCH_NAME}' --username "$$USERNAME" --git-tag-prefix '${_GIT_TAG_PREFIX}' 
