steps:
- name: 'anzx-docker.artifactory.gcp.anz/sfdx-cli:7.20.1'
  id: 'sfdx-version'
  args: [ '--version' ]

- name: 'anzx-docker.artifactory.gcp.anz/sfdx-cli:7.20.1'
  id: 'sfdx-help'

options:
  workerPool: 'anz-cx-cloudbuild-dev-5ef683/custom-workers-dev-pool'

