substitutions:
  # git tag prefix for production deployments.
  _GIT_TAG_PREFIX: 'prod-'

options:
  workerPool: 'anz-cx-cloudbuild-dev-5ef683/custom-workers-dev-pool'

steps:
- id: git_init
  name: 'gcr.io/cloud-builders/git'
  waitFor: ['-']
  entrypoint: bash
  args:
  - -c
  - |
    # Attempt to fetch all tags
    git fetch --unshallow
    git branch -a

- id: 'code_quality_pmd'
  waitFor: [ '-' ]
  name: 'hub.artifactory.gcp.anz/jamesmoriarty/pmd:6.18.0'
  args: [
    'pmd',
    '-R', '/workspace/rulesets/apex/quickstart.xml',
    '-d', '.',
    '-l', 'apex',
    '-f', 'textcolor'
  ]

- id: 'decrypt_key'
  name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=keys/sfdx-auth-url-production.encrypted.txt
  - --plaintext-file=keys/sfdx-auth-url-production.txt
  - --location=global
  # TODO the keyring and key are not updated for the production environment.
  - --keyring=cloudbuild-keyring
  - --key=salesforce-prod-authentication-key

- id: 'deploy_to_production'
  waitFor: ['git_init', 'decrypt_key', 'code_quality_pmd']
  name: 'anzx-docker.artifactory.gcp.anz/salesforce/salesforce-builder:new'
  entrypoint: bash
  args:
  - -c
  - |
    # The value of USERNAME does not matter, as long as the alias is aligned between the deploy
    # command and the sfdx credential store.
    USERNAME='ASDF'
    sfdx force:auth:sfdxurl:store --sfdxurlfile 'keys/sfdx-auth-url-production.txt' --setalias "$$USERNAME" --json
    exec /workspace/scripts/cicd.sh --branch '${BRANCH_NAME}' --username "$$USERNAME" --git-tag-prefix '${_GIT_TAG_PREFIX}' 

- id: 'push_tag'
  waitFor: ['deploy_to_production']
  name: 'gcr.io/cloud-builders/git'
  args:
  - -c
  - |
    [[ -e tag.txt ]] || exit
    TAG=$$(cat tag.txt)
    git tag "$$TAG"
    git push origin "$$TAG"
