options:
  workerPool: 'anz-cx-cloudbuild-dev-5ef683/custom-workers-dev-pool'

steps:
- id: git_init
  name: 'gcr.io/cloud-builders/git'
  waitFor: ['-']
  entrypoint: bash
  args:
  - -c
  - |
    # Attempt to fetch all tags
    git fetch --unshallow
    git branch -a

- id: 'Decrypt the SFDX Key Using gcloud KMS'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - |
    if [[ '$BRANCH_NAME' == develop || '$BRANCH_NAME' == feature/* ]]; then
      ENV='systest'
    elif [[ '$BRANCH_NAME' == master || '$BRANCH_NAME' == release/* ]]; then
      ENV='staging'
    fi
    if [[ -n $${ENV+x} ]]; then
      gcloud kms decrypt \
        --ciphertext-file=keys/sfdx-auth-url-"$$ENV".encrypted.txt \
        --plaintext-file=keys/sfdx-auth-url-"$$ENV".txt \
        --location=global \
        --keyring=cloudbuild-keyring \
        --key=salesforce-cli-authentication-key
    fi

- id: 'Deploy to environment'
  name: 'anzx-docker.artifactory.gcp.anz/salesforce/salesforce-builder:new'
  entrypoint: bash
  args:
  - -c
  - |
    # The value of USERNAME does not matter, as long as the alias is aligned between the deploy
    # command and the sfdx credential store.
    USERNAME='ASDF'
    if [[ '$BRANCH_NAME' == develop || '$BRANCH_NAME' == feature/* ]]; then
      sfdx force:auth:sfdxurl:store --sfdxurlfile 'keys/sfdx-auth-url-systest.txt' --setalias "$$USERNAME" --json
    elif [[ '$BRANCH_NAME' == master || '$BRANCH_NAME' == release/* ]]; then
      sfdx force:auth:sfdxurl:store --sfdxurlfile 'keys/sfdx-auth-url-staging.txt' --setalias "$$USERNAME" --json
    fi
    exec /workspace/scripts/cicd.sh \
      --branch '${BRANCH_NAME}' \
      --username "$$USERNAME"

- id: 'Code Quality (PMD)'
  waitFor: [ '-' ]
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'run',  '-v', '/workspace:/workdir', 'hub.artifactory.gcp.anz/jamesmoriarty/pmd:6.18.0',
    'pmd',
      '-R', 'rulesets/apex/quickstart.xml',
      '-d', '.',
      '-l', 'apex',
      '-f', 'textcolor'
  ]
