import RecordPage from "pageObjects/recordPage";
import QualityWorkbenchHomePage from "pageObjects/qualityWorkbenchHomePage";
import CoachesWorkbenchHomePage from "pageObjects/coachesWorkbenchHomePage";
import LwcRecordCreationForm from "pageObjects/lwcRecordCreationForm";
import QualityAssessmentSharingModal from "pageObjects/qualityAssessmentSharingModal";
import { UserRole, SObject, SObjectAPIName, OwnerType } from "constants/enums";
import { App, AppTab } from "constants/appsDefinition";
import { navigateToAppAndTab } from "utils/navigationUtils";
import * as qaPageUtils from "utils/qualityAssessmentPageUtils";
import * as commonUtils from "utils/commonUtils";
import BaseRecordForm from "pageObjects/baseRecordForm";
import accountData from "data/accountData";
import { FieldSectionIndex } from "types/layout";
import IAssignNewOwner from "interfaces/IAssignNewOwner";

type ListViewTitle =
  | "Outstanding Quality Assessments"
  | "My Quality Assessments"
  | "Assurance Tasks";

type CreationContext = "modal" | "related-list";

export default class QualityAssessment implements IAssignNewOwner {
  protected readonly userRole: UserRole;
  protected readonly sobject: SObject;
  public caseNumber: string | undefined;
  public qaNumber: string | undefined;

  constructor(userRole: UserRole) {
    this.sobject = SObject.Quality_Assessment;
    this.userRole = userRole;
    this.caseNumber = undefined;
    this.qaNumber = undefined;
  }

  async verifyListViewByTitle(listViewTitle: ListViewTitle): Promise<void> {
    const qualityWorkbenchHomePageRoot = await utam.load(
      QualityWorkbenchHomePage
    );
    const listView = await qualityWorkbenchHomePageRoot.getListViewByTitle(
      listViewTitle
    );

    // verify user can view list view
    expect(await listView.isVisible()).toBeTruthy();
  }

  async openAutoGeneratedQA(): Promise<void> {
    const qualityWorkbenchHomePageRoot = await utam.load(
      QualityWorkbenchHomePage
    );

    // by default the first QA in this list view should be the one that auto generated by Case Close Trigger
    const listView = await qualityWorkbenchHomePageRoot.getListViewByTitle(
      "Outstanding Quality Assessments"
    );

    const firstRecord = await listView.getListViewRowByIndex(1);
    expect(await firstRecord.isVisible()).toBeTruthy();

    // Quality Assess Number is table row header (1st column) in Outstanding Quality Assessments list view
    this.qaNumber = await firstRecord.getRowHeaderContent();

    // Related Case is 5th column in Outstanding Quality Assessments list view
    const caseNumber = await firstRecord.getContentByRowCellIndex(5);
    // verify the auto created QA record linked to the desired case by case number
    expect(caseNumber).toEqual(this.caseNumber);

    // open the first record and redirect to the QA record page
    await firstRecord.clickRowHeader();

    const domDocument = utam.getCurrentDocument();
    await domDocument.waitFor(async () =>
      (await domDocument.getUrl()).includes(SObjectAPIName.Quality_Assessment)
    );
  }

  async createQAFromListView(listViewTitle: ListViewTitle): Promise<void> {
    await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    const qualityWorkbenchHomePageRoot = await utam.load(
      QualityWorkbenchHomePage
    );
    const listView = await qualityWorkbenchHomePageRoot.getListViewByTitle(
      listViewTitle
    );

    await listView.clickNew();
    await browser.pause(2000);
    await this.createQA("modal", true);
  }

  async createQAFromCaseRelatedList(): Promise<void> {
    // search case number in global search and redirect
    await commonUtils.searchRecordInGlobalSearchAndRedirect(this.caseNumber!);

    // load Case record flexi page
    const recordPageRoot = await utam.load(RecordPage);
    const caseRecordPage = await recordPageRoot.getCaseRecordPage();
    const qaList = await caseRecordPage.getQualityAssessmentsRelatedList();

    await qaList.clickButtonByTitle("New");
    await browser.pause(2000);
    await this.createQA("related-list", false);
  }

  async createQAFromAccountRelatedList(): Promise<void> {
    // search Account in global search and redirect
    await commonUtils.searchRecordInGlobalSearchAndRedirect(accountData.ocvId);

    // load Account record flexi page
    const recordPageRoot = await utam.load(RecordPage);
    const accountRecordPage = await recordPageRoot.getAccountRecordPage();
    const qaList = await accountRecordPage.getQualityAssessmentsRelatedList();

    await browser.pause(1000);
    await qaList.clickDropdownButtonByTitle("New");
    await browser.pause(2000);
    await this.createQA("related-list", true);
  }

  async createQA(
    context: CreationContext,
    caseNumberRequired: boolean
  ): Promise<void> {
    const recordCreationFormRoot = await utam.load(LwcRecordCreationForm);

    let baseRecordForm: BaseRecordForm;

    if (context === "modal") {
      baseRecordForm = await recordCreationFormRoot.getModalBaseRecordForm();
    } else {
      baseRecordForm =
        await recordCreationFormRoot.getRelatedListBaseRecordForm();
    }

    const recordLayout = await baseRecordForm.getRecordLayout();

    if (caseNumberRequired) {
      // Related Case
      const relatedCaseField = await commonUtils.getFieldFromRecordLayout(
        recordLayout,
        [1, 3, 1]
      );
      const lookup = await relatedCaseField.getLookup();
      const baseCombobox = await lookup.getBaseCombobox();
      await baseCombobox.searchLookupAndSelect(this.caseNumber!);
    }

    // Interaction Type
    await commonUtils.selectPicklistOnRecordLayout(
      recordLayout,
      [1, 3, 2],
      [2, 8]
    );

    await baseRecordForm.clickFooterButton("Save");
    await browser.pause(3000);
  }

  async assignNewOwner(
    newOwnerType: OwnerType,
    newOwnerName: string
  ): Promise<void> {
    // Owner field index on layout
    const ownerFieldIndex: FieldSectionIndex = [2, 1, 1];

    await commonUtils.assignNewOwner(
      this.sobject,
      ownerFieldIndex,
      newOwnerType,
      newOwnerName
    );
  }

  async evaluate(status: "Referred" | "Complete"): Promise<void> {
    const baseRecordForm = (await qaPageUtils.getRecordForm())!;
    const recordLayout = await baseRecordForm.getRecordLayout();

    // select Yes for all below fields to complete evaluation of a Quality Assessment
    // Risk and Compliance Category
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 1, 1], 2);

    // Preparation and Framing
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 3, 1], 2);

    // Connection and Trust
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 4, 1], 2);

    // Discover and Align
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 5, 1], 2);

    // Insights and Focus
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 6, 1], 2);

    // Actions and Momentum
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 7, 1], 2);

    // Accountability and Next Steps
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 8, 1], 2);

    // Energy and Adaptability
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 9, 1], 2);

    // Finishing Touches
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [4, 10, 1], 2);

    // Rating
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [3, 1, 2], 2);

    // Compliance Outcome
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [3, 2, 1], 2);

    // Interaction Type
    await commonUtils.selectPicklistOnRecordLayout(recordLayout, [2, 2, 2], 2);

    // Status
    if (status === "Referred") {
      // Referred
      await commonUtils.selectPicklistOnRecordLayout(
        recordLayout,
        [2, 5, 1],
        4
      );

      // Sub-Status - Compliance Review
      await commonUtils.selectPicklistOnRecordLayout(
        recordLayout,
        [2, 5, 2],
        2
      );
    } else {
      // Complete
      await commonUtils.selectPicklistOnRecordLayout(
        recordLayout,
        [2, 5, 1],
        5
      );

      // Sub-Status - Evaluation Completed
      await commonUtils.selectPicklistOnRecordLayout(
        recordLayout,
        [2, 5, 2],
        2
      );
    }

    await baseRecordForm.clickFooterButton("Save");
    await browser.pause(3000);
  }

  async shareTo(username: string): Promise<void> {
    const recordPageRoot = await utam.load(RecordPage);
    const qaRecordPage = await recordPageRoot.getQualityAssessmentRecordPage();

    const highlightPanel = await qaRecordPage.getHighlights();
    const layout = await highlightPanel.getRecordLayout();
    const highlight = await layout.getHighlights2();
    const actionRibbon = await highlight.getActionsRibbon();
    const sharingButton = await actionRibbon.getActionRendererWithTitle(
      "Sharing"
    );
    await sharingButton.clickButton();

    // load sharing modal
    const qualityAssessmentSharingModalRoot = await utam.load(
      QualityAssessmentSharingModal
    );

    await browser.pause(2000);
    await qualityAssessmentSharingModalRoot.clickSearchBox();
    await qualityAssessmentSharingModalRoot.search(username);
    await browser.pause(2000);

    await qualityAssessmentSharingModalRoot.clickResult(username);
    await qualityAssessmentSharingModalRoot.save();

    // wait for page reload
    await browser.pause(2000);
  }

  async verifySharedView(): Promise<void> {
    await navigateToAppAndTab(App.Coaches_Workbench, AppTab.Home);

    const coachesWorkbenchHomePageRoot = await utam.load(
      CoachesWorkbenchHomePage
    );

    // use webdriverio API to scroll to Completed Quality Assessments element
    const elem = await $("span[title='Completed Quality Assessments']");
    await elem.scrollIntoView();

    const completedQARelatedList =
      await coachesWorkbenchHomePageRoot.getCompletedQARelatedList();
    const qa = await completedQARelatedList.getQualityAssessmentByNumber(
      this.qaNumber!
    );

    // verify shared QA is visible
    expect(await qa.isVisible()).toBeTruthy();
  }

  async loadAndSortAssuranceTask(): Promise<void> {
    await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    const qualityWorkbenchHomePageRoot = await utam.load(
      QualityWorkbenchHomePage
    );
    const listView = await qualityWorkbenchHomePageRoot.getListViewByTitle(
      "Assurance Tasks"
    );

    // make list view sort descending
    const relatedTo = await listView.getListViewHeaderByTitle("Related To");
    await relatedTo.sort();
    await browser.pause(2000);

    const sortingDirection = await relatedTo.getSortingDirection();

    // if ascending, click again to force to descending
    if (sortingDirection === "Sorted Ascending") {
      await relatedTo.sort();
      await browser.pause(2000);
    }
  }

  async verifyAssuranceTask(): Promise<void> {
    await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    const qualityWorkbenchHomePageRoot = await utam.load(
      QualityWorkbenchHomePage
    );
    const listView = await qualityWorkbenchHomePageRoot.getListViewByTitle(
      "Assurance Tasks"
    );

    const firstRecord = await listView.getListViewRowByIndex(1);

    // Related To is the second td element in Assurance Tasks list view
    const relatedToQA = await firstRecord.getContentByRowCellIndex(2);
    expect(relatedToQA).toEqual(this.qaNumber);
  }

  async verifyEscalatedQAInCoachesWorkbench(): Promise<void> {
    await navigateToAppAndTab(App.Coaches_Workbench, AppTab.Home);
    const coachesWorkbenchHomePageRoot = await utam.load(
      CoachesWorkbenchHomePage
    );
    const listView = await coachesWorkbenchHomePageRoot.getListViewByTitle(
      "Compliance Reviews"
    );

    // verify user can view list view
    expect(await listView.isVisible()).toBeTruthy();

    // make list view sort descending
    const qaColumnHeader = await listView.getListViewHeaderByTitle(
      "Quality Assessment Name"
    );
    await qaColumnHeader.sort();
    await browser.pause(2000);

    const sortingDirection = await qaColumnHeader.getSortingDirection();

    // if ascending, click again to force to descending
    if (sortingDirection === "Sorted Ascending") {
      await qaColumnHeader.sort();
      await browser.pause(2000);
    }

    const firstRecord = await listView.getListViewRowByIndex(1);

    // Quality Assessment Name is the th element in Assurance Tasks list view
    const escalatedQANumber = await firstRecord.getRowHeaderContent();
    expect(escalatedQANumber).toEqual(this.qaNumber);

    // open and redirect this QA
    await firstRecord.clickRowHeader();
    await browser.pause(2000);

    const domDocument = utam.getCurrentDocument();
    await domDocument.waitFor(async () =>
      (await domDocument.getUrl()).includes(SObjectAPIName.Quality_Assessment)
    );
  }
}
