FROM selenium/standalone-chrome:4.1.3-20220327
ENTRYPOINT ["/bin/bash","-l","-c"]
USER root
RUN mkdir /app
WORKDIR /app
#RUN chmod 777 /app

ARG NODEJS_VERSION_MAJOR=14
ARG ARTIFACTORY_URL="https://artifactory.gcp.anz/artifactory"
ARG NPM_ARTIFACTORY=artifactory.gcp.anz
ENV NPM_CONFIG_REGISTRY=https://${NPM_ARTIFACTORY}/artifactory/api/npm/npmjs-org

RUN rm -rf /etc/apt/sources.list.d/* && \
    sed -i "s~http://security.ubuntu.com/ubuntu~${ARTIFACTORY_URL}/ubuntu-security~g" /etc/apt/sources.list && \
    sed -i "s~http://archive.ubuntu.com/ubuntu~${ARTIFACTORY_URL}/au-archive-ubuntu~g" /etc/apt/sources.list && \
    apt-get update -y -qq && \
    apt-get install -y -qq --no-install-recommends python2.7 make g++ git zip vim lsb-release net-tools
RUN set -eux && \
    curl -fsSL --output /tmp/nodesource.gpg.key https://artifactory.gcp.anz/artifactory/nodesource/gpgkey/nodesource.gpg.key && \
    NODESOURCE_KEY='/usr/share/keyrings/nodesource.gpg' && \
    gpg --dearmor -o "${NODESOURCE_KEY}" < /tmp/nodesource.gpg.key && \
    rm -rf /tmp/nodesource.gpg.key && \
    DISTRO="$(lsb_release -s -c)" && \
    REPO="node_${NODEJS_VERSION_MAJOR}.x" && \
    echo "deb [signed-by=${NODESOURCE_KEY}] https://artifactory.gcp.anz/artifactory/nodesource/${REPO} ${DISTRO} main" > /etc/apt/sources.list.d/nodesource.list && \
    echo "deb-src [signed-by=${NODESOURCE_KEY}] https://artifactory.gcp.anz/artifactory/nodesource/${REPO} ${DISTRO} main" >> /etc/apt/sources.list.d/nodesource.list && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends nodejs="${NODEJS_VERSION_MAJOR}".\* && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    node --version


ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=4096

###trial to instal chromedirver
# RUN npm config set strict-ssl false
# RUN npm config set registry https://artifactory.gcp.anz/artifactory/api/npm/npm-virtual/
# RUN npm config set registry https://artifactory.gcp.anz:443/artifactory/EA-IS-virtual/
# RUN npm config set strict-ssl false
# RUN npm config set proxy http://localhost:3128/
# RUN npm config set http-proxy http://localhost:3128/
# RUN npm config set https-proxy http://localhost:3128/

# RUN npm install -g chromedriver --detect_chromedriver_version
# RUN apt-get install chromium-chromedriver -yq
# RUN apt-get install chromium -yq


ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=4096


COPY salesforce/automation-test/package.json /app
COPY salesforce/automation-test/.npmrc /app

RUN chown -hR seluser:seluser /app
RUN chmod 777 /app
USER 1200

RUN npm config set strict-ssl false
RUN npm config set registry https://artifactory.gcp.anz:443/artifactory/EA-IS-virtual/

EXPOSE 4444
EXPOSE 9515