export const EMP_TYPE_MAP = {
  EMPLOYMENT_BASIS_UNSPECIFIED: "Unspecified",
  EMPLOYMENT_BASIS_FULL_TIME: "Full Time",
  EMPLOYMENT_BASIS_PART_TIME: "Part Time",
  EMPLOYMENT_BASIS_CASUAL: "Casual",
  EMPLOYMENT_BASIS_CONTRACTOR: "Contractor"
};

export const ITEM_TYPE_MAP = {
  INCOME_TYPE_BASE_SALARY: "Base Salary",
  INCOME_TYPE_SALARY_WAGES: "Base Salary",
  INCOME_TYPE_BONUS: "Bonuses",
  INCOME_TYPE_COMMISSION: "Commission",
  INCOME_TYPE_OVERTIME: "Overtime"
};

export const RENTAL_INCOME_TYPE_MAP = {
  INCOME_TYPE_RESIDENTIAL_STANDARD_LEASE: "Contracted",
  INCOME_TYPE_RESIDENTIAL_PRIVATE_LEASE: "Private Arrangement",
  INCOME_TYPE_RESIDENTIAL_SHORT_STAY: "Short Stay"
};

export const WAGE_ORDER = [
  "INCOME_TYPE_BASE_SALARY",
  "INCOME_TYPE_OVERTIME",
  "INCOME_TYPE_COMMISSION",
  "INCOME_TYPE_BONUS"
];
