/**
 * @author Smruti Khobragade
 * @since Aug/2025
 * @description class for RBM Interaction Constants
 */

public with sharing class RBMInteractionConstants {
  public static final String INTERACTION_STATUS_OPEN = 'Open';
  public static final String INTERACTION_STATUS_CLOSED_COMPLETED = 'Closed - Completed';
  public static final String INTERACTION_STATUS_CLOSED_FOLLOWUP = 'Closed - Follow Up Interaction';
  public static final String INTERACTION_STATUS_CLOSED_WITHDRAWN = 'Closed - Withdrawn';
  public static final String INTERACTION_BROKER_ATTENDEE = 'Broker';
}
