const salesforceSecretNames = {
  master: "sf-platform-np-preprod",
  develop: "sf-platform-np-test",
  "release/preprod": "h-salesforce-prod-preprod",
  "release/consumer-key": "h-salesforce-prod-ca-consumerkey",
  "release/cert": "h-salesforce-prod-cert",
  release: "sf-platform-np-test",
  "epic/anzx-bau": "sf-platform-np-anzxbau",
  "epic/cfaasepic": "sf-platform-np-cfaasepic",
  "epic/cmos-a": "sf-platform-np-cmosa",
  "epic/cmos-b": "sf-platform-np-cmosb",
  "epic/cmos-bau": "h-salesforce-np-cmosbaudev",
  "epic/cmos-omnistudio": "sf-platform-np-cmosomni",
  "epic/cmos-r2": "sf-platform-np-idrdev",
  "epic/ccrm-dev": "sf-platform-np-ccrmdev",
  "epic/ccrm-c360": "sf-platform-np-c360dev",
  "epic/dcrm": "sf-platform-np-dcrm",
  "epic/logging-monitoring": "sf-platform-np-logging-monitoring",
  "epic/qa-v2": "sf-platform-np-qav2",
  "epic/pega-smarts": "sf-platform-np-pegasmarts",
  "epic/auto-kyc": "sf-platform-np-autokyc",
  "epic/ribbon": "sf-platform-np-ribbon",
  "epic/boh-view": "sf-platform-np-bohview",
  "epic/manage-party": "sf-platform-np-managept",
  "epic/cfaas": "sf-platform-np-cfaas",
  "epic/cloud-events": "sf-platform-np-cloudevent",
  "epic/h1-account": "sf-platform-np-h1accounts",
  "epic/plat": "sf-platform-np-platform",
  "epic/twilio": "sf-platform-np-twilio",
  "epic/h1-statements": "sf-platform-np-h1stment",
  "epic/receive-and-distribute-ingested-leads":
    "sf-platform-np-receive-and-distribute-ingested-leads",
  "epic/credit-referral": "sf-platform-np-credit-referral",
  "epic/view-sop": "sf-platform-np-viewsop",
  "epic/interaction-v2": "sf-platform-np-interactionv2",
  "epic/view-umi": "sf-platform-np-viewumi",
  "epic/appointment-booking": "sf-platform-np-appointment-booking",
  "epic/payto": "sf-platform-np-payto",
  "epic/apiupliftforaccountandtransaction": "sf-platform-np-apiuplift",
  "epic/bdm-login": "sf-platform-np-bdmlogin",
  "epic/loan-app": "sf-platform-np-loan-app",
  "epic/search-customer": "sf-platform-np-searchcustomer",
  "epic/inapp-complaint": "sf-platform-np-inappcomp",
  "epic/bohleads": "sf-platform-np-bohleads",
  "epic/disputes": "sf-platform-np-disputes",
  "epic/signauth": "sf-platform-np-signauth",
  "epic/coachnudges": "sf-platform-np-coachnudge",
  "epic/connectid": "sf-platform-np-connectid",
  "epic/join-salesforce-ciba": "sf-platform-np-ciba",
  "epic/bdm-app-overview": "sf-platform-np-brokermain",
  "epic/transaction-income": "sf-platform-np-trnscncome",
  "epic/disputeq-auto": "sf-platform-np-disputeq",
  "epic/ccrmintact": "sf-platform-np-ccrmintact",
  "epic/profileupdate": "sf-platform-np-profileupd",
  "epic/kycqa-auto-grading": "sf-platform-np-kycqagrade"
};

const brokerSecretNames = {
  master: "sf-platform-np-preprod-broker",
  develop: "sf-platform-np-test-broker",
  "epic/brokernfr": "sf-platform-np-brokernfr-broker",
  "epic/replicate-data": "sf-platform-np-replicate-data-broker",
  "epic/loan-apps": "sf-platform-np-loan-apps-broker",
  "epic/cb-km-login": "sf-platform-np-commercial-broker"
};

export { salesforceSecretNames, brokerSecretNames };
