import Auth from "common/Auth";
import { navigateToAppAndTab } from "utils/navigationUtils";
import { UserRole, OwnerType } from "constants/enums";
import { App, AppTab } from "constants/appsDefinition";
import GeneralEnquiry from "common/cases/GeneralEnquiry";
import ANZXComplaint from "common/cases/ANZXComplaint";
import QualityAssessment from "common/QualityAssessment";
import qualityAssessmentData from "data/qualityAssessmentData";
import caseData from "data/caseData";

describe("AR-4500: Quality Workbench", async (): Promise<void> => {
  // pre test steps
  before(async (): Promise<void> => {
    // max viewport
    await browser.maximizeWindow();
  });

  beforeEach(async (): Promise<void> => {
    await browser.takeScreenshot();
    await browser.pause(500);
  });

  afterEach(async (): Promise<void> => {
    await browser.takeScreenshot();
    await browser.pause(500);
  });

  describe("AR-10346: Quality Analyst processes Quality Assessment for General Enquiry case", async (): Promise<void> => {
    const generalEnquiryCase = new GeneralEnquiry(UserRole.QUALITY_ANALYST);
    const qualityAssessment = new QualityAssessment(UserRole.QUALITY_ANALYST);

    it("Login as Quality Aanalyst", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.QUALITY_ANALYST);
    });

    it("Go to Quality Workbench and Case Tab", async (): Promise<void> => {
      await navigateToAppAndTab(App.Quality_Workbench, AppTab.Cases);
    });

    it("Create a General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.create(caseData);
      // get the created case number and pass in to QA
      qualityAssessment.caseNumber = generalEnquiryCase.caseNumber;
    });

    it("Update General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.update();
    });

    it("Close General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.close();
    });

    it("Go to Quality Workbench Home Page", async (): Promise<void> => {
      await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    });

    it("View My Quality Assessments List View", async (): Promise<void> => {
      await qualityAssessment.verifyListViewByTitle("My Quality Assessments");
    });

    it("View Assurance Tasks List View", async (): Promise<void> => {
      await qualityAssessment.verifyListViewByTitle("Assurance Tasks");
    });

    it("View Outstanding Quality Assessments List View", async (): Promise<void> => {
      await qualityAssessment.verifyListViewByTitle(
        "Outstanding Quality Assessments"
      );
    });

    it("Open auto generated QA by Case Closure from Outstanding Quality Assessments List View", async (): Promise<void> => {
      await qualityAssessment.openAutoGeneratedQA();
    });

    it("Create QA Manually from Outstanding Quality Assessments List View", async (): Promise<void> => {
      await qualityAssessment.createQAFromListView(
        "Outstanding Quality Assessments"
      );
    });

    it("Create QA Manually from Case Related List", async (): Promise<void> => {
      await qualityAssessment.createQAFromCaseRelatedList();
    });

    it("Create QA Manually from Person Account Record Page", async (): Promise<void> => {
      await qualityAssessment.createQAFromAccountRelatedList();
    });

    it("Logout", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });
  });

  describe.skip("AR-10347: Quality Analyst processes Quality Assessment for ANZ Plus Complaint case", async (): Promise<void> => {
    const anzxComplaintCase = new ANZXComplaint(UserRole.QUALITY_ANALYST);
    const qualityAssessment = new QualityAssessment(UserRole.QUALITY_ANALYST);

    it("Login as Quality Aanalyst", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.QUALITY_ANALYST);
    });

    it("Go to Coaches Workbench and Case tab", async (): Promise<void> => {
      await navigateToAppAndTab(App.Quality_Workbench, AppTab.Cases);
    });

    it("Create a ANZ Plus Complaint Case", async (): Promise<void> => {
      await anzxComplaintCase.create(caseData);
      // get the created case number and pass in to QA
      qualityAssessment.caseNumber = anzxComplaintCase.caseNumber;
    });

    it("Close ANZ Plus Complaint Case", async (): Promise<void> => {
      await anzxComplaintCase.close();
    });

    it("Go to Quality Workbench Home Page", async (): Promise<void> => {
      await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    });

    it("View Outstanding Quality Assessments List View", async (): Promise<void> => {
      await qualityAssessment.verifyListViewByTitle(
        "Outstanding Quality Assessments"
      );
    });

    it("Create QA Manually from Case Related List", async (): Promise<void> => {
      await qualityAssessment.createQAFromCaseRelatedList();
    });

    it("Logout", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });
  });

  describe("AR-10348: Quality Analyst completes Quality Assessment and shares with Coach", async (): Promise<void> => {
    const generalEnquiryCase = new GeneralEnquiry(UserRole.QUALITY_ANALYST);
    const qualityAssessment = new QualityAssessment(UserRole.QUALITY_ANALYST);

    it("Login as Coach", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.COACH);
    });

    it("Go to Quality Workbench and Case Tab", async (): Promise<void> => {
      await navigateToAppAndTab(App.Coaches_Workbench, AppTab.Cases);
    });

    it("Create a General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.create(caseData);
      // get the created case number and pass in to QA
      qualityAssessment.caseNumber = generalEnquiryCase.caseNumber;
    });

    it("Update General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.update();
    });

    it("Close General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.close();
    });

    it("Logout as Coach", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });

    it("Login as Quality Analyst", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.QUALITY_ANALYST);
    });

    it("Go to Quality Workbench Home Page", async (): Promise<void> => {
      await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    });

    it("Open auto generated QA by Case Closure", async (): Promise<void> => {
      await qualityAssessment.openAutoGeneratedQA();
    });

    it("Assign to Quality Analyst Self", async (): Promise<void> => {
      await qualityAssessment.assignNewOwner(
        OwnerType.Users,
        qualityAssessmentData.newQualityAnalystName
      );
    });

    it("Evaluate the QA and Complete", async (): Promise<void> => {
      await qualityAssessment.evaluate("Complete");
    });

    it("Share the Completed QA to Coach with Read-Only", async (): Promise<void> => {
      await qualityAssessment.shareTo(qualityAssessmentData.newCoachName);
    });

    it("Logout as Quality Analyst", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });

    it("Login as Coach", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.COACH);
    });

    it("Coach View Shared QA", async (): Promise<void> => {
      await qualityAssessment.verifySharedView();
    });

    it("Logout as Coach", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });
  });

  describe("AR-10349: Quality Analyst escalates Quality Assessment to Coach Lead who shares with Coach", async (): Promise<void> => {
    const generalEnquiryCase = new GeneralEnquiry(UserRole.QUALITY_ANALYST);
    const qualityAssessment = new QualityAssessment(UserRole.QUALITY_ANALYST);

    it("Login as Coach", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.COACH);
    });

    it("Go to Quality Workbench and Case Tab", async (): Promise<void> => {
      await navigateToAppAndTab(App.Coaches_Workbench, AppTab.Cases);
    });

    it("Create a General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.create(caseData);
      // get the created case number and pass in to QA
      qualityAssessment.caseNumber = generalEnquiryCase.caseNumber;
    });

    it("Update General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.update();
    });

    it("Close General Enquiry Case", async (): Promise<void> => {
      await generalEnquiryCase.close();
    });

    it("Logout as Coach", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });

    it("Login as Quality Analyst", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.QUALITY_ANALYST);
    });

    it("Go to Quality Workbench Home Page", async (): Promise<void> => {
      await navigateToAppAndTab(App.Quality_Workbench, AppTab.Home);
    });

    it("Open auto generated QA by Case Closure", async (): Promise<void> => {
      await qualityAssessment.openAutoGeneratedQA();
    });

    it("Evaluate the QA and Escalate", async (): Promise<void> => {
      await qualityAssessment.evaluate("Referred");
    });

    it("View Assurance Task List View for Escalated QA", async (): Promise<void> => {
      await qualityAssessment.loadAndSortAssuranceTask();
    });

    it("Verify Assurance Task List View for Escalated QA", async (): Promise<void> => {
      await qualityAssessment.verifyAssuranceTask();
    });

    it("Logout as Quality Analyst", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });

    it("Login as Coach Lead", async (): Promise<void> => {
      // login as test user
      await Auth.loginSalesforceAsRole(UserRole.COACH_LEAD);
    });

    it("Coach Lead View the Escalated QA in Coaches Workench", async (): Promise<void> => {
      await qualityAssessment.verifyEscalatedQAInCoachesWorkbench();
    });

    it("Coach Lead Evaluate the Escalated QA and Complate", async (): Promise<void> => {
      await qualityAssessment.evaluate("Complete");
    });

    it("Share the Completed QA to Coach with Read-Only", async (): Promise<void> => {
      await qualityAssessment.shareTo(qualityAssessmentData.newCoachName);
    });

    it("Logout as Coach Lead", async (): Promise<void> => {
      // log out test user
      await Auth.logoutSalesforce();
    });
  });
});
