name: Release Stage

on:
  workflow_call:
    inputs:
      DEPLOYMENT_ENVIRONMENT:
        description: "Deployment Environment"
        required: true
        type: string
      DEPLOYMENT_TITLE:
        description: "Deployment Title"
        required: true
        type: string
      PUBLISH_EVENT_ENV_NAME:
        description: "Publish Event Environment Name"
        required: true
        type: string
      JOB_NAME:
        description: "Job Name"
        required: true
        type: string
      RELEASE_NAME:
        description: "Release Name"
        required: true
        type: string
      JOB_ID_FILE_NAME_INPUT:
        description: "Job ID File Name from previous stage"
        required: false
        type: string
    outputs:
      JOB_ID_FILE_NAME:
        description: "Job ID File Name for next stage"
        value: ${{ jobs.execute.outputs.JOB_ID_FILE_NAME }}
    secrets:
      token:
        required: true

permissions:
  contents: "write"
  id-token: "write"

jobs:
  execute:
    outputs:
      JOB_ID_FILE_NAME: ${{ steps.set-job-id.outputs.JOB_ID_FILE_NAME }}
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:2.1.1"
      options: --user root
      volumes:
        - ${{ github.workspace }}/release:/opt/harness-delegate/release
    runs-on: anzx-default
    concurrency:
      group: "salesforce-release-${{ inputs.RELEASE_NAME }}"
      cancel-in-progress: false
    name: "${{ inputs.DEPLOYMENT_TITLE }}"
    environment: "${{ inputs.DEPLOYMENT_ENVIRONMENT }}"
    env:
      SERVICE_ACCOUNT: "h-sf-primary-prod@anz-x-bootstrap-prod-3b7a6d.iam.gserviceaccount.com"
      RELEASE_NAME: "${{ inputs.RELEASE_NAME }}"
      RUN_ATTEMPT: "${{ github.run_attempt }}"
      ARTIFACTORY_SECRET_NAME: "sf-platform-prod-artifact"
      PREPROD_SECRET_NAME: "sf-platform-prod-preprod"
      PROD_CONSUMER_KEY_SECRET_NAME: "sf-platform-prod-ca-consumerkey"
      PROD_CERT_SECRET_NAME: "sf-platform-prod-cert"
      PREPROD_DEPLOYMENT_STEP: ${{ inputs.DEPLOYMENT_ENVIRONMENT == 'prod-release-start' }}
      PROD_VALIDATION_STEP: ${{ inputs.DEPLOYMENT_ENVIRONMENT == 'prod-validation' }}
      PROD_DEPLOYMENT_STEP: ${{ inputs.DEPLOYMENT_ENVIRONMENT == 'prod-deployment' }}
      PUBLISH_EVENT_ENV_NAME: ${{ inputs.PUBLISH_EVENT_ENV_NAME }}
      STAGE_NAME: ${{ inputs.DEPLOYMENT_ENVIRONMENT }}
      JOB_NAME: ${{ inputs.JOB_NAME }}
      REPO_NAME: ${{ github.event.repository.name }}
      PROD_DEPLOY_USERNAME: "tech.gcb@anzx.com"
      PROD_URL: "https://anz.my.salesforce.com"
      JOB_ID_FILE_NAME: ${{ inputs.JOB_ID_FILE_NAME_INPUT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "true"
          token: ${{ secrets.token }}

      - name: Link plugin
        run: |
          cd /opt/harness-delegate/sf-plugin
          sf plugins link .

      - name: Environment Varibales Debug
        run: |
          echo "DEBUG: RUN_ATTEMPT=${{ env.RUN_ATTEMPT }}"
          echo "DEBUG: PREPROD_DEPLOYMENT_STEP=${{ env.PREPROD_DEPLOYMENT_STEP }}"
          echo "DEBUG: PROD_VALIDATION_STEP=${{ env.PROD_VALIDATION_STEP }}"
          echo "DEBUG: PROD_DEPLOYMENT_STEP=${{ env.PROD_DEPLOYMENT_STEP }}"
          echo "DEBUG: STAGE_NAME=${{ env.STAGE_NAME }}"
          echo "DEBUG: REPO_NAME=${{ env.REPO_NAME }}"
          echo "DEBUG: JOB_NAME=${{ env.JOB_NAME }}"

      - name: "OIDC Authentication (Salesforce Harness Delegate Service Account)"
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "${{ env.SERVICE_ACCOUNT }}"

      - name: "Retrieve GSM Credentials"
        id: secrets
        uses: "google-github-actions/get-secretmanager-secrets@v1"
        with:
          secrets: |-
            preprod:projects/anz-x-gh-sf-prod-be3529/secrets/${{ env.PREPROD_SECRET_NAME }}/versions/latest
            prod-consumer-key:projects/anz-x-gh-sf-prod-be3529/secrets/${{ env.PROD_CONSUMER_KEY_SECRET_NAME }}/versions/latest
            prod-cert:projects/anz-x-gh-sf-prod-be3529/secrets/${{ env.PROD_CERT_SECRET_NAME }}/versions/latest
            artifactory:projects/anz-x-gh-sf-prod-be3529/secrets/${{ env.ARTIFACTORY_SECRET_NAME }}/versions/latest

      - name: Prepare ENV Variables
        run: |
          echo CLEANING_JOB="false" >> $GITHUB_ENV
          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV
          lastTag="$( git describe --abbrev=0 --tags --match master* )"
          echo BASE_REF_LAST_TAG="$lastTag" >> $GITHUB_ENV

      - name: Set Job ID File Name
        id: set-job-id
        if: ${{ inputs.JOB_NAME != 'prod-deployment' }}
        run: |
          JOB_ID_NAME="release-${{ env.RELEASE_NAME }}-${{ env.RUN_ATTEMPT }}"
          JOB_ID_NAME=$(echo "$JOB_ID_NAME" | sed 's/[^a-zA-Z0-9-]/-/g')
          echo "JOB_ID_FILE_NAME=$JOB_ID_NAME" >> $GITHUB_ENV
          echo "JOB_ID_FILE_NAME=$JOB_ID_NAME" >> $GITHUB_OUTPUT
          echo "Created Job ID: $JOB_ID_NAME"

      - name: Run ${{ inputs.DEPLOYMENT_ENVIRONMENT }}
        id: deployment
        run: |
          node --no-warnings ci/workflows/Orchestrations/release.mjs "${{ steps.secrets.outputs.preprod }}" "${{ steps.secrets.outputs.prod-consumer-key }}" "${{ steps.secrets.outputs.prod-cert }}" "${{ steps.secrets.outputs.artifactory }}"
          echo CLEANING_JOB="true" >> $GITHUB_ENV

      - name: Cleaning | Create Tag
        run: |
          node --no-warnings ci/workflows/Orchestrations/release.mjs "${{ steps.secrets.outputs.preprod }}" "${{ steps.secrets.outputs.prod-consumer-key }}" "${{ steps.secrets.outputs.prod-cert }}" "${{ steps.secrets.outputs.artifactory }}"

      - name: Publish Deployment Event
        if: ${{ always() && !cancelled() && steps.deployment.outcome != 'skipped' && env.PUBLISH_EVENT_ENV_NAME != '' }}
        uses: anzx/github-reusable-actions/publish-deployment-event@main
        with:
          environment: "${{ env.PUBLISH_EVENT_ENV_NAME }}"
          service_name: "salesforce"
          service_account: "${{ env.SERVICE_ACCOUNT }}"
          event_status: ${{ steps.deployment.outcome }}
