# This re-usable workflow is to control steps for Salesforce Validation
name: Salesforce Validation Reusable Workflow
on:
  workflow_call:
    inputs:
      sfdx_name:
        required: false
        description: "Secret Name as an Input"
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  validation:
    name: Validation ${{inputs.sfdx_name}}
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:1.2.1"
      options: --user root
    runs-on: anzx-default
    steps:
      - name: Link SGD plugin
        run: |
          cd /opt/harness-delegate/.local/share/sf
          sf plugins:link node_modules/sfdx-git-delta/bin

      - name: NPM package Version | node, sfdx, sf, sgd version
        run: |
          echo "node version: $(node -v)"
          echo "sf version: $(sf -v)"
          echo "sf plugins: $(sf plugins)"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: ENV vars
        run: |
          baseRef="${{ github.base_ref }}"
          echo BASE_REF="$baseRef" >> $GITHUB_ENV
          echo BRANCH_NAME="${{ github.head_ref }}" >> $GITHUB_ENV
          echo PR_NUMBER="${{ github.event.number }}" >> $GITHUB_ENV
          echo DRAFT_PR="${{ github.event.pull_request.draft }}" >> $GITHUB_ENV
          echo SPECIFIED_TEST_PR="${{ contains( toJson(github.event.pull_request.labels), 'Run Specified Tests') }}" >> $GITHUB_ENV
          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV
          echo REPO_NAME="${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo JOB_NAME="${{ inputs.sfdx_name }}" >> $GITHUB_ENV

          lastTag="$( git describe --abbrev=0 --tags --match $baseRef* )"
          echo BASE_REF_LAST_TAG="$lastTag" >> $GITHUB_ENV
          echo ARTIFACTORY_SECRET_NAME="sf-platform-np-artifact" >> $GITHUB_ENV

      - name: Find Secret Names
        run: |
          sfdxURL="${{ inputs.sfdx_name }}"
          projectId=anz-x-bootstrap-np-487e09

          if [[ "$sfdxURL" == "" ]];then
            sfdxURL=$( node ci/workflows/Orchestrations/findSecret.mjs )
          fi

          if [[ "$sfdxURL" == "sf-platform-np-"* ]];then
            projectId=anz-x-gh-sf-nonprod-ea5caa
          fi

          echo "$sfdxURL"
          echo SECRET_NAME="$sfdxURL" >> $GITHUB_ENV
          echo PROJECT_ID="$projectId" >> $GITHUB_ENV

      - name: Retrieve GSM Credentials
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/${{ env.PROJECT_ID }}/secrets/${{ env.SECRET_NAME}}/versions/latest
            artifactory:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/${{ env.ARTIFACTORY_SECRET_NAME }}/versions/latest

      - name: Run Validation
        run: |
          node --no-warnings ci/workflows/Orchestrations/validation.mjs "${{ steps.secrets.outputs.sfdxurl }}" "${{ steps.secrets.outputs.artifactory }}"
          echo WHICH_JOB="clean" >> $GITHUB_ENV

      - name: Code Coverage and Cleaning
        run: |
          node --no-warnings ci/workflows/Orchestrations/validation.mjs
