name: Automation-Test

on:
  schedule:
    - cron: "0 5 * * 1-5" # Run at 5AM weekday

jobs:
  automation-test:
    runs-on: [self-hosted, salesforce]
    steps:
      - name: Trigger Harness Job
        run: |
          docker run --rm \
            anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:ede3323 \
            --harness-api-key=CiUALvObyFFSMIO9lC8YUwdvtU6X9/W2dq5AtNmcdgjPME4s6z48ErYBAPO28TLr1ZTTpb/DjiyYN2gj/Ta3b58qEbtlWRKPW69xbx4+2/Bwt84iol8Hbf688qjPZ3i5wa4t025jlfP6EG3um//xpOsssZ9TCYkkqMvtdupzMqxbiOO8uu35eQnesfZKVc05xWVcz5DKpMrLeKe7R7Tsw2yaLHrlhPzwmfp9Gary1D75zhHl59d32udkZyeROJ49naqS6LvOJwx/IV6pfj05zE11U0P2euCBFH18KWP5wRk= \
            --kms-key=projects/anz-x-services-platdev-fcf8c0/locations/global/keyRings/developer-experience/cryptoKeys/anz-x-services-platdev-fcf8c0_github-runner-common-secrets \
            --application-name=salesforce \
            --target-name=salesforce-automation-test-np \
            --target-type=WORKFLOW \
            --wait
