name: BlackDuck 🦆 Scan

on:
  pull_request:
    paths:
      - .github/workflows/blackduck.yml # Run on change to scan, or packages, in master
      - "package.json"
    branches:
      - master
  push:
    paths:
      - .github/workflows/blackduck.yml # Run on change to scan, or packages, in develop
      - "package.json"
    branches:
      - develop
  schedule:
    - cron: "57 2 * * SAT" # Run every Saturday between 2-3am

jobs:
  blackduck:
    runs-on: [self-hosted, org]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "12"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: "Install npm packages"
        run: |
          mv ci.npmrc .npmrc
          npm ci

      - name: "🦆 Black Duck Scan"
        run: |
          set -x
          if [[ "${GITHUB_REF}" == refs/pull/* ]]
          then
            PR_NUMBER=$(echo "${GITHUB_REF}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          else
            REF="${GITHUB_REF}"
          fi
          # NOTE: the following is not actually a secret, but an encrypted blob
          docker run --rm \
            anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:latest \
            --harness-api-key=CiUALvObyCdx/LOa/QDKwMlYRpDEQJ2qHzw/3NU+5JIyDg48PqtSErYBADVs6ThOwBR9GqQTYYHPL9YK25KzNciYQ53CcRQrLeU4yqEPUOmFgrRWvHF3woJ9HKQ+gVtpxQ16dXt4Kql2dPkFcitZGHX5rXugw0AX29OhdaKt7xYT1FxvFyhK78g72ZXvkCvqnvI1gKMTEMPqKyv3Nz4uKVCRi1pLM10R1DckF8gPZo00dX4bhlBczeJU3ySdwohTe0OH3sKcUTTXACaLw08k4MR0MykgW70nR9lLrh6sqk4= \
            --kms-key=projects/anz-x-services-platdev-fcf8c0/locations/global/keyRings/developer-experience/cryptoKeys/anz-x-services-platdev-fcf8c0_github-runner-common-secrets \
            --application-name=secscan \
            --target-name=BlackduckScanCI \
            --target-type=PIPELINE \
            --variables="GIT_COMMIT_SHA=${GITHUB_SHA};GIT_REF=${REF};REPO=github.com/${GITHUB_REPOSITORY};PULL_REQUEST=${PR_NUMBER}" \
            --wait
