name: BlackDuck 🦆 Scan

on:
  pull_request:
    branches:
      - master
      - release
      - develop
  push:
    branches:
      - develop
  schedule:
    - cron: "57 2 * * *" # Run every day between 2-3am

concurrency:
  group: "blackduck-check-${{ github.event.repository.name }}-${{ github.event.pull_request.number || github.ref_name || 'schedule' }}"
  cancel-in-progress: true

jobs:
  blackduck-scan:
    uses: anzx/sec-domain-actions/.github/workflows/bd-scan-ci.yaml@stable
    secrets: inherit

  slack-msg:
    name: Send Slack Message
    if: ${{ always() && (needs.blackduck-scan.result == 'success' || needs.blackduck-scan.result == 'failure') }}
    needs: [blackduck-scan]
    uses: ./.github/workflows/_prepare_notification.yaml
    with:
      job_name: "Blackduck"
      job_status: "${{ needs.blackduck-scan.result }}"
      slack_channel: "sf-security"
