name: BlackDuck 🦆 Scan

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop
  schedule:
    - cron: "57 2 * * *" # Run every day between 2-3am

jobs:
  scan:
    uses: anzx/sec-domain-actions/.github/workflows/bd-scan-ci.yaml@stable
    secrets: inherit

  status:
    if: ${{ always() }}
    needs:
      - scan
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Set BASE_REF
        run: echo BASE_REF=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV

      - name: Slack message
        shell: bash
        env:
          BLACKDUCK_STATUS: ${{ needs.scan.result }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          if [[ $BLACKDUCK_STATUS == success ]];then
            status=:white_check_mark:
          else
            status=:X:
          fi

          if [[ $GITHUB_HEAD_REF == '' ]];then
            GITHUB_HEAD_REF="$BASE_REF"
          fi

          TodayDate="$(TZ=Australia/Melbourne date +%F\|%H:%M)"
          actionURL="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"

          IDENTITY_TOKEN=$(curl -H "Metadata-Flavor: Google" 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://platform-notify.platform-notify.services-platdev.x.gcpnp.anz&format=full&licenses=TRUE')
          curl -H "Authorization: Bearer ${IDENTITY_TOKEN}" --data '{"channel":"sf-security","templateID":"ghasfsecurity","args":{"startdatetime":"'${TodayDate}'","passed":"'${status}'","branch":"'$GITHUB_HEAD_REF'","checkname":"Blackduck","reponame":"Salesforce","resultsurl":"'${actionURL}'"}}' https://platform-notify.platform-notify.services-platdev.x.gcpnp.anz/slack
