name: ✍️ Check PR
on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-title:
    name: 🎫 Check Title for Jira Ticket
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Checkout Action Repo
        uses: actions/checkout@v2
        with:
          repository: anzx/pr-title-action
          ref: v2
          token: ${{ secrets.SALESFORCE_PR_TITLE_ACTION_TOKEN }}
          path: .github/actions/pr-title-action

      - name: Check PR Title for Ticket
        uses: ./.github/actions/pr-title-action
        with:
          jira-project: "(ABT|IDR|ANZX|APRART|AR|CC|RIB)"
