# This workflow scans a Salesforce project using Checkmarx
name: Checkmarx Scan

on:
  pull_request:
    branches:
      - develop
      - master
      - epic/*
      - release
    paths:
      - force-app/**
      - .github/workflows/checkmarx-scan.yml
  schedule:
    - cron: "0 9 * * 0-4" # Run every day between 8-9 pm

concurrency:
  group: "checkmarx-check-${{ github.event.repository.name }}-${{ github.event.pull_request.number || github.ref_name || 'schedule' }}"
  cancel-in-progress: true

jobs:
  checkmarx-scan:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Set env variables
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          GITHUB_BRANCH=$GITHUB_HEAD_REF
          BUG_TRACKER=Sarif

          if [[ $GITHUB_BRANCH == '' ]];then
            GITHUB_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          fi

          if [[ $EVENT_NAME == 'pull_request' ]]; then
            BUG_TRACKER=GitHubPull
          fi

          echo GITHUB_BRANCH=$GITHUB_BRANCH >> $GITHUB_ENV
          echo BUG_TRACKER=$BUG_TRACKER >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - env:
          # Do not send Google metadata server requests to the Squid proxy
          NO_PROXY: ".googleapis.com,.internal,169.254.169.254"
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            CHECKMARX_URL:projects/36540621485/secrets/ghr-checkmarx-url/versions/2
            CHECKMARX_USERNAME:projects/36540621485/secrets/ghr-checkmarx-username/versions/2
            CHECKMARX_PASSWORD:projects/36540621485/secrets/ghr-checkmarx-password/versions/2

      - name: Checkmarx CxFlow Action
        id: checkmarx
        uses: anzx/platform-actions-checkmarx-cxflow@main
        with:
          project: github.com.anzx.salesforce
          team: /CxServer/Security/Salesforce
          checkmarx_url: ${{ steps.secrets.outputs.CHECKMARX_URL }}
          checkmarx_username: ${{ steps.secrets.outputs.CHECKMARX_USERNAME }}
          checkmarx_password: ${{ steps.secrets.outputs.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.SECSCAN_CHECKMARX_SECRET }}
          github_token: ${{ secrets.SALESFORCE_CXFLOW_GH_TOKEN }}
          incremental: false
          break_build: true
          bug_tracker: ${{ env.BUG_TRACKER }}
          zip_exclude: \.git\/.*,\.git\-hooks\/.*,\.github\/.*,ci\/.*,config\/.*,coverage\/.*,data\/.*,mdapi\-source\/.*,misc\/.*,node_modules\/.*
          params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ env.GITHUB_BRANCH }} --merge-id=${{ github.event.number }} --severity=High --checkmarx.scan-resubmit=true --checkmarx.scan-queuing=true

  slack-msg:
    name: Send Slack Message
    if: ${{ always() && (needs.checkmarx-scan.result == 'success' || needs.checkmarx-scan.result == 'failure') }}
    needs: [checkmarx-scan]
    uses: ./.github/workflows/_prepare_notification.yaml
    with:
      job_name: "Checkmarx"
      job_status: "${{ needs.checkmarx-scan.result }}"
      slack_channel: "sf-security"
