name: codeowners-plus-lint
on:
  pull_request:
jobs:
  codeowners-plus-lint:
    runs-on: anzx-default
    steps:
      - uses: actions/checkout@v4
      - uses: docker://anzx-docker.artifactory.gcp.anz/github-codeowners-plus:latest
        with:
          args: lint
