# This workflow deploys docs files to salesforce-docs
name: Create docs

on:
  workflow_dispatch:

permissions:
  contents: "write"
  id-token: "write"

env:
  RUN_ID: "${{ github.run_id }}"

jobs:
  create_docs:
    strategy:
      fail-fast: false
      matrix:
        which-doc:
          - NAME: "Sysl"
            SLEEP: 0
            PLUGIN_COMMAND: "../plugin/bin/run doc:sysl -f config/doc-def.json -p config/panther-manual-desc.json -u staging"
            CREATED_FOLDER_PATH: "salesforce/docs/sysl"

          - NAME: "Schema"
            SLEEP: 10
            PLUGIN_COMMAND: "../plugin/bin/run doc:schema -f config/doc-def.json -u staging"
            CREATED_FOLDER_PATH: "salesforce/docs/schema"

          - NAME: "Access"
            SLEEP: 20
            PLUGIN_COMMAND: "../plugin/bin/run doc:access -f config/doc-def.json -u staging"
            CREATED_FOLDER_PATH: "salesforce/docs/access"

    runs-on: anzx-default-np
    concurrency:
      group: "${{ matrix.which-doc.NAME }}-${{ github.run_id }}"
      cancel-in-progress: true
    steps:
      - name: Echo informations
        run: |
          echo "which-doc: ${{ matrix.which-doc.NAME }}" 
          sleep ${{ matrix.which-doc.SLEEP }}

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Checkout doc plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.SALESFORCE_DOC_GEN_TOKEN }}
          path: plugin

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: Retrieve required secrets
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/sf-platform-np-sysl/versions/latest
            artifactory:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/sf-platform-np-artifact/versions/latest

      - name: Install npm packages
        working-directory: salesforce
        run: |
          mv ci.npmrc .npmrc
          npm ci -f

      - name: Install yarn
        working-directory: plugin
        shell: bash
        run: |
          npm install --global yarn --registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/
          yarn config set registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/

      - name: 🧱 Check yarn version
        working-directory: plugin
        run: yarn --version
        shell: bash

      - name: Install plugin
        working-directory: plugin
        run: |
          mv ci.yarnrc .yarnrc
          rm -rf node_modules && yarn install --frozen-lockfile
        shell: bash

      - name: Create auth files with SFDX_URL secret
        working-directory: salesforce
        shell: bash
        run: echo ${{ steps.secrets.outputs.sfdxurl }} > ./SFDX_URL_STAGING.txt

      - name: Authenticate all orgs in SFDX CLI
        working-directory: salesforce
        run: npx sf org login sfdx-url -a staging --sfdx-url-file=./SFDX_URL_STAGING.txt

      - name: Generate ${{ matrix.which-doc.NAME }} docs
        working-directory: salesforce
        shell: bash
        run: |
          ${{ matrix.which-doc.PLUGIN_COMMAND }}

      - if: "${{ matrix.which-doc.NAME == 'sysl' }}"
        name: Check if there is any missed information
        working-directory: salesforce
        run: |
          errorsText=$( cat ./docs/sysl/sysl-error.txt )
          if [[ $errorsText == *'missed'* ]]; then
            cat ./docs/sysl/sysl-error.txt
          fi

      - name: Upload to artifactory
        run: |
          artifactFoldername="${{ matrix.which-doc.NAME }}-${{ env.RUN_ID }}"
          mkdir "$artifactFoldername"
          cp -r ${{ matrix.which-doc.CREATED_FOLDER_PATH }} "$artifactFoldername/"
          zip -r "$artifactFoldername.zip" "$artifactFoldername"
          curl -H "Authorization: Bearer ${{ steps.secrets.outputs.artifactory }}" -X PUT -T "$artifactFoldername.zip" "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$artifactFoldername.zip"

  raise-pr:
    strategy:
      fail-fast: false
      matrix:
        which-doc:
          - NAME: "Sysl"
            REMOVE_PATH: "salesforce-docs/sysl/salesforce.edg.sysl"
            CREATED_FOLDER_PATH: "sysl/salesforce.edg.sysl"
            DESTINATION_FOLDER_PATH: "salesforce-docs/sysl/"
            ADD_PATH: "sysl/salesforce.edg.sysl"

          - NAME: "Schema"
            REMOVE_PATH: "salesforce-docs/docs/governance/schema"
            CREATED_FOLDER_PATH: "schema"
            DESTINATION_FOLDER_PATH: "salesforce-docs/docs/governance/"
            ADD_PATH: "docs/governance/schema"

          - NAME: "Access"
            REMOVE_PATH: "salesforce-docs/docs/governance/access"
            CREATED_FOLDER_PATH: "access"
            DESTINATION_FOLDER_PATH: "salesforce-docs/docs/governance/"
            ADD_PATH: "docs/governance/access"

    runs-on: anzx-default-np
    needs: [create_docs]
    steps:
      - name: Checkout salesforce-docs repo
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-docs
          token: ${{ secrets.SALESFORCE_DOCS_TOKEN }}
          path: salesforce-docs

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: Retrieve required secret
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            artifactory:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/sf-platform-np-artifact/versions/latest

      - name: Download zip file
        run: |
          artifactFoldername="${{ matrix.which-doc.NAME }}-${{ env.RUN_ID }}"
          echo "ARTIFACT_NAME=$artifactFoldername" >> $GITHUB_ENV
          curl -H "Authorization: Bearer ${{ steps.secrets.outputs.artifactory }}" -O "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$artifactFoldername.zip"
          unzip "$artifactFoldername.zip"

      - name: Copy ${{ matrix.which-doc.NAME }} files
        run: |
          rm -rf ${{ matrix.which-doc.REMOVE_PATH }}
          cp -r "${{env.ARTIFACT_NAME}}/${{matrix.which-doc.CREATED_FOLDER_PATH}}" ${{ matrix.which-doc.DESTINATION_FOLDER_PATH }}

      - name: Create new branch on anzx/salesforce-docs and commit ${{matrix.which-doc.NAME}} files
        working-directory: salesforce-docs
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{env.ARTIFACT_NAME}}
          git add ${{matrix.which-doc.ADD_PATH}}
          git commit -m "Update ${{matrix.which-doc.NAME}} files"
          git push origin ${{env.ARTIFACT_NAME}}

      - name: Install GH
        uses: "anzx/github-reusable-actions/setup-gh-cli@main"
        with:
          gh-cli-version: "2.50.0"

      - name: Create a PR on anzx/salesforce-docs
        working-directory: salesforce-docs
        shell: bash
        run: |
          sleep 10
          WHICH_JOB="${{matrix.which-doc.NAME}}"
          ACTION_URL="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          if git branch | grep -q -w ${{env.ARTIFACT_NAME}}; then
            gh pr create -B master -H ${{env.ARTIFACT_NAME}} -t "Update $WHICH_JOB files for Salesforce" -b "An automated PR to update $WHICH_JOB files from $ACTION_URL";
          fi
          echo "✅ Pull Request raised"
        env:
          GITHUB_TOKEN: ${{ secrets.SALESFORCE_DOCS_TOKEN }}
