# This workflow deployssysl files to salesforce-docs
name: Create Sysl files

on:
  push:
    branches:
      - develop

jobs:
  create_sysl:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Checkout salesforce-docs repo
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-docs
          token: ${{ secrets.SALESFORCE_DOCS_TOKEN }}

      - name: Checkout doc plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.SALESFORCE_DOC_GEN_TOKEN }}
          path: plugin

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: Install hub
        run: |
          curl -SL https://artifactory.gcp.anz/artifactory/github/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz -o hub.tar.gz && \
          tar zxf hub.tar.gz && mv -v ./hub-linux-amd64-2.14.2/bin/hub /usr/bin/hub && \
          chmod -v a+x /usr/bin/hub && \
          rm -v hub.tar.gz

      - name: Install npm packages
        working-directory: salesforce
        run: |
          mv ci.npmrc .npmrc
          npm ci

      - name: Install yarn
        working-directory: plugin
        shell: bash
        run: |
          npm install --global yarn --registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/
          yarn config set registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/

      - name: 🧱 Check yarn version
        working-directory: plugin
        run: yarn --version
        shell: bash

      - name: Install plugin
        working-directory: plugin
        run: |
          mv ci.yarnrc .yarnrc
          rm -rf node_modules && yarn install --frozen-lockfile
        shell: bash

      - name: SFDXURL
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-sysl-np/versions/1

      - name: "Create auth files with SFDX_URL secret"
        working-directory: salesforce
        shell: bash
        run: echo ${{ steps.secrets.outputs.sfdxurl }} > ./SFDX_URL_STAGING.txt

      - name: "Authenticate all orgs in SFDX CLI"
        working-directory: salesforce
        run: npx sfdx force:auth:sfdxurl:store -a staging --sfdxurlfile=./SFDX_URL_STAGING.txt

      - name: Generate Sysl docs
        working-directory: salesforce
        shell: bash
        run: |
          ../plugin/bin/run doc:sysl -f config/doc-def.json -p config/panther-manual-desc.json -u staging

      - name: Check if there is any missed information
        working-directory: salesforce
        run: |
          errorsText=$( cat ./docs/sysl/sysl-error.txt )
          if [[ $errorsText == *'missed'* ]]; then
            cat ./docs/sysl/sysl-error.txt
            exit 1
          fi

      - name: Copy docs
        run: |
          rm -rf ./sysl/salesforce.business.sysl
          rm -rf ./sysl/salesforce.edg.sysl

          cp -r salesforce/docs/sysl/salesforce.business.sysl ./sysl/
          cp -r salesforce/docs/sysl/salesforce.edg.sysl ./sysl/

      - name: Create new branch on anzx/salesforce-docs
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${GITHUB_RUN_ID}
          git add sysl/salesforce.business.sysl sysl/salesforce.edg.sysl
          git commit -m "Update Sysl files"
          git push origin ${GITHUB_RUN_ID}

      - name: Create a PR on anzx/salesforce-docs
        shell: bash
        run: |
          if git branch | grep -q -w ${GITHUB_RUN_ID}; then hub pull-request -b master -h ${GITHUB_RUN_ID} --no-edit -m "${GITHUB_REF#refs/heads/}-${GITHUB_RUN_ID} Sysl Update" -m "An automated PR to update sysl documentation from https://github.com/anzx/salesforce/pull/${{ github.event.number }}"; fi
          echo "✅ Pull Request raised"
        env:
          GITHUB_TOKEN: ${{ secrets.SALESFORCE_DOCS_TOKEN }}
