# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Deploy

# This workflow will only run on pushes to master and develop
on:
  push:
    branches:
      - develop
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest

    env:
      BASE_BRANCH: ${{ github.base_ref }}

    steps:
      - name: "Create auth files with SFDX_URL secret"
        shell: bash
        run: |
          echo ${{ secrets.SYSTEST}} > ./SFDX_URL_SYSTEST.txt
          echo ${{ secrets.CMOSDEV}} > ./SFDX_URL_CMOSDEV.txt

      - name: "Authenticate all orgs in SFDX CLI"
        run: |
          sfdx force:auth:sfdxurl:store -a cmosdev --sfdxurlfile=./SFDX_URL_CMOSDEV.txt
          sfdx force:auth:sfdxurl:store -a systest --sfdxurlfile=./SFDX_URL_SYSTEST.txt

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Generate package"
        id: package
        shell: bash
        run: |
          git fetch --tags 
          ci/package.sh

      - uses: actions/upload-artifact@v1
        if: ${{ steps.package.outputs.ARTEFACT_GENERATED }}
        with:
          name: package
          path: ./artefact/

      - name: "Deploy Changes"
        shell: bash
        run: ci/deploy.sh
        env:
          DEPLOY_ROOT: ./artefact/
          BUILD_COMMAND: deploy

      - name: "Tag Release"
        shell: bash
        run: |
          echo "${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
          TAG="${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
          git tag "$TAG"
          git push origin "$TAG"

  create_documentation:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest
    needs: build_and_deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-docs
          token: ${{ secrets.ORG_GITHUB_TOKEN }}

      - name: Checkout doc plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          path: plugin

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: Install plugin
        working-directory: plugin
        shell: bash
        run: yarn install

      - name: "Create auth files with SFDX_URL secret"
        shell: bash
        run: echo ${{ secrets.SYSTEST}} > ./SFDX_URL_SYSTEST.txt

      - name: "Authenticate all orgs in SFDX CLI"
        run: sfdx force:auth:sfdxurl:store -a systest --sfdxurlfile=./SFDX_URL_SYSTEST.txt

      - name: Reindex sidebar
        run: |
          npm i lodash@4.17.19
          node reindex

      - name: Generate schema and access docs
        working-directory: salesforce
        shell: bash
        run: |
          ../plugin/bin/run doc:schema -f config/doc-def.json -u systest
          ../plugin/bin/run doc:access -f config/doc-def.json -u systest

      - name: Copy docs
        run: |
          rm -rf ./docs/governance/access
          rm -rf ./docs/governance/schema
          mkdir -p ./docs/governance/
          cp -r salesforce/docs/* ./docs/governance/

      - name: Generate apex docs
        working-directory: salesforce
        shell: bash
        run: |
          find force-app/main/default/classes -mindepth 2 -type f -print -exec cp {} force-app/main/default/classes \;
          java -jar apexdoc/apexdoc.jar -s force-app/main/default/classes -t apexdoc/ -a apexdoc/banner.htm -h apexdoc/home.htm

      - name: Copy apex docs
        run: |
          rm -rf ./docs/static/ApexDocumentation
          mkdir -p ./docs/static/
          cp -r salesforce/apexdoc/ApexDocumentation ./docs/static/

      - name: Create new branch on anzx/salesforce-docs
        uses: EndBug/add-and-commit@v4
        with:
          add: "docs/static docs/governance sidebars.js"
          author_name: github-actions
          message: "Update salesforce documentation"
          ref: "doc/plugin-update"
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}

      - name: Create a PR on anzx/salesforce-docs
        shell: bash
        run: |
          hub pull-request -b master -h doc/plugin-update --no-edit -m "${GITHUB_REF##*/}-${GITHUB_RUN_ID} Release Update" -m "An automated PR to update access and schema documentation from https://github.com/anzx/salesforce/releases/tag/${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
