name: Salesforce Deployment

on:
  push:
    branches:
      - "develop"
      - "epic/*"

permissions:
  contents: "write"
  id-token: "write"

jobs:
  Deployment:
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:1.4.1"
      options: --user root
    runs-on: anzx-default-np
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "true"
          token: ${{ secrets.SALESFORCE_ACTIONS_CHECKOUT_TOKEN }}
          path: salesforce

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: ENV vars
        working-directory: salesforce
        run: |
          baseRef="$(echo ${GITHUB_REF#refs/heads/})"
          echo BASE_REF="$baseRef" >> $GITHUB_ENV
          echo RUN_ID="${GITHUB_RUN_ID}" >> $GITHUB_ENV
          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV
          echo REPO_NAME="${{ github.event.repository.name }}" >> $GITHUB_ENV

          lastTag="$( git describe --abbrev=0 --tags --match $baseRef* )"
          echo BASE_REF_LAST_TAG="$lastTag" >> $GITHUB_ENV

      - name: Find Secret Names
        working-directory: salesforce
        run: |
          sfdxURL=$( node ci/workflows/Orchestrations/findSecret.mjs )
          projectId=anz-x-bootstrap-np-487e09

          if [[ "$sfdxURL" == "sf-platform-np-"* ]];then
            projectId=anz-x-gh-sf-nonprod-ea5caa
          fi

          echo "$sfdxURL"
          echo SECRET_NAME="$sfdxURL" >> $GITHUB_ENV
          echo PROJECT_ID="$projectId" >> $GITHUB_ENV
          echo ARTIFACTORY_SECRET_NAME="sf-platform-np-artifact" >> $GITHUB_ENV

      - name: Retrieve GSM Credentials
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/${{ env.PROJECT_ID }}/secrets/${{ env.SECRET_NAME }}/versions/latest
            artifactory:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/${{ env.ARTIFACTORY_SECRET_NAME }}/versions/latest

      - name: Checkout salesforce-plugin repo
        uses: actions/checkout@v4
        with:
          repository: anzx/salesforce-plugin
          token: ${{ secrets.SALESFORCE_PLUGIN_CHECKOUT_TOKEN }}
          path: salesforce-plugin

      - name: Install plugin
        working-directory: salesforce-plugin
        shell: bash
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile
          yarn build
          sf plugins link .

      - name: Run Deployment
        working-directory: salesforce
        run: |
          node --no-warnings ci/workflows/Orchestrations/deployment.mjs "${{ steps.secrets.outputs.sfdxurl }}"
          echo WHICH_JOB="clean" >> $GITHUB_ENV

      - name: Cleanup
        working-directory: salesforce
        run: |
          node --no-warnings ci/workflows/Orchestrations/deployment.mjs

  Create-tag:
    runs-on: anzx-default
    needs: [Deployment]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag Creation
        run: |
          baseRef="$(echo ${GITHUB_REF#refs/heads/})"
          runId="${GITHUB_RUN_ID}"
          newTag="$baseRef-$runId"
          git tag "$newTag"
          git push origin "$newTag"

          echo "New created tag is: $newTag"
