# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Deploy

# This workflow will only run on pushes to master and develop
on:
  push:
    branches:
      - master
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest

    env:
      BASE_BRANCH: ${{ github.base_ref }}

    steps:
      - name: "Create auth files with SFDX_URL secret"
        shell: bash
        run: |
          echo ${{ secrets.SYSTEST}} > ./SFDX_URL_SYSTEST.txt
          echo ${{ secrets.STAGING}} > ./SFDX_URL_STAGING.txt

      - name: "Authenticate all orgs in SFDX CLI"
        run: |
          sfdx force:auth:sfdxurl:store -a staging --sfdxurlfile=./SFDX_URL_STAGING.txt
          sfdx force:auth:sfdxurl:store -a systest --sfdxurlfile=./SFDX_URL_SYSTEST.txt

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Generate package"
        shell: bash
        run: |
          git fetch --tags 
          ci/package.sh

      - name: "Deploy Changes"
        id: deploy
        shell: bash
        run: |
          ci/deploy.sh
          if [ -d ./artefact/ ]; then ARTEFACT_GENERATED='true' ; fi
        env:
          DEPLOY_ROOT: ./artefact/
          BUILD_COMMAND: deploy

      - uses: actions/upload-artifact@v1
        if: ${{ steps.deploy.outputs.ARTEFACT_GENERATED }}
        with:
          name: package
          path: ./artefact/

      - name: "Tag Release"
        shell: bash
        run: |
          echo "${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
          TAG="${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
          git tag "$TAG"
          git push origin "$TAG"
