# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Deploy

# This workflow will only run on pushes to master , develop and epic/*
on:
  push:
    branches:
      - develop
      - master
      - epic/*

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest
    outputs:
      IS_SANDBOX_SECRET_SET: ${{ steps.checksecret.outputs.IS_SANDBOX_SECRET_SET }}
    steps:
      - name: Set Branch Name
        run: echo BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV

      - name: Set Sandbox Name
        run: |
          if [ ${{ env.BRANCH_NAME }} == 'develop' ]; then echo SANDBOX_NAME=$(echo SYSTEST) >> $GITHUB_ENV; elif [ ${{ env.BRANCH_NAME }} == 'master' ]; then echo SANDBOX_NAME=$(echo STAGING) >> $GITHUB_ENV; else echo SANDBOX_NAME=$(echo ${{ env.BRANCH_NAME }} |  tr -d '-' | tr 'a-z' 'A-Z' | cut -d'/' -f 2 | cut -c1-10) >> $GITHUB_ENV; fi

      - name: Check whether the sandbox secret exists
        id: checksecret
        env:
          MY_SECRET: ${{ secrets[env.SANDBOX_NAME] }}
        run: |
          echo "IS_SANDBOX_SECRET_SET: ${{ env.MY_SECRET != '' }}"
          echo "::set-output name=IS_SANDBOX_SECRET_SET::${{ env.MY_SECRET != '' }}" 
          echo ${{ steps.checksecret.outputs.IS_SANDBOX_SECRET_SET }}

  build_and_deploy:
    needs: [prepare]
    if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest

    steps:
      - name: Set Branch Name
        run: echo BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV
      - name: Set Sandbox Name
        run: |
          if [ ${{ env.BRANCH_NAME }} == 'develop' ]; then echo SANDBOX_NAME=$(echo SYSTEST) >> $GITHUB_ENV; elif [ ${{ env.BRANCH_NAME }} == 'master' ]; then echo SANDBOX_NAME=$(echo STAGING) >> $GITHUB_ENV; else echo SANDBOX_NAME=$(echo ${{ env.BRANCH_NAME }} |  tr -d '-' | tr 'a-z' 'A-Z' | cut -d'/' -f 2 | cut -c1-10) >> $GITHUB_ENV; fi

      - name: "Authenticate the org"
        shell: bash
        run: |
          echo 'Authenticating ${{ env.SANDBOX_NAME }}'
          echo ${{ secrets[env.SANDBOX_NAME] }} > ./SFDX_URL_${{ env.SANDBOX_NAME }}.txt
          sfdx force:auth:sfdxurl:store -a ${{ env.SANDBOX_NAME }} --sfdxurlfile=./SFDX_URL_${{ env.SANDBOX_NAME }}.txt

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Generate package"
        id: package
        shell: bash
        run: |
          git fetch --tags 
          ci/package.sh

      - uses: actions/upload-artifact@v1
        if: ${{ steps.package.outputs.ARTEFACT_GENERATED }}
        with:
          name: package
          path: ./artefact/

      - name: "Deploy Changes"
        shell: bash
        run: ci/deploy.sh
        env:
          DEPLOY_ROOT: ./artefact/
          BUILD_COMMAND: deploy
          ORG_NAME: ${{ env.SANDBOX_NAME }}

      - name: "Tag Release"
        shell: bash
        run: |
          echo "${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
          TAG="${GITHUB_REF##*/}-${GITHUB_RUN_ID}"
          git tag "$TAG"
          git push origin "$TAG"

  create_documentation:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest
    needs: build_and_deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-docs
          token: ${{ secrets.ORG_GITHUB_TOKEN }}

      - name: Checkout doc plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          path: plugin

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: Install plugin
        working-directory: plugin
        shell: bash
        run: yarn install

      - name: "Create auth files with SFDX_URL secret"
        shell: bash
        run: echo ${{ secrets.SYSTEST}} > ./SFDX_URL_SYSTEST.txt

      - name: "Authenticate all orgs in SFDX CLI"
        run: sfdx force:auth:sfdxurl:store -a systest --sfdxurlfile=./SFDX_URL_SYSTEST.txt

      - name: Generate schema and access docs
        working-directory: salesforce
        shell: bash
        run: |
          ../plugin/bin/run doc:schema -f config/doc-def.json -u systest
          ../plugin/bin/run doc:access -f config/doc-def.json -u systest
          ../plugin/bin/run doc:sysl -f config/doc-def.json -u systest

      - name: Copy docs
        run: |
          rm -rf ./docs/governance/access
          rm -rf ./docs/governance/schema
          rm -rf ./sysl/salesforce.edg.sysl
          mkdir -p ./docs/governance/
          mkdir -p ./sysl/
          cp -r salesforce/docs/access ./docs/governance/
          cp -r salesforce/docs/schema ./docs/governance/
          cp -r salesforce/docs/sysl ./

      - name: Generate apex docs
        working-directory: salesforce
        shell: bash
        run: |
          find force-app/main/default/classes -mindepth 2 -type f -print -exec cp {} force-app/main/default/classes \;
          java -jar apexdoc/apexdoc.jar -s force-app/main/default/classes -t apexdoc/ -a apexdoc/banner.htm -h apexdoc/home.htm

      - name: Copy apex docs
        run: |
          rm -rf ./docs/static/ApexDocumentation
          mkdir -p ./docs/static/
          cp -r salesforce/apexdoc/ApexDocumentation ./docs/static/

      - name: Reindex sidebar
        run: |
          npm i lodash@4.17.19
          node reindex

      - name: Create new branch on anzx/salesforce-docs
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${GITHUB_RUN_ID}
          git add docs/static docs/governance sidebars.js sysl/
          git commit -m "Update salesforce documentation"
          git push origin ${GITHUB_RUN_ID}

      - name: Create a PR on anzx/salesforce-docs
        shell: bash
        run: |
          if git branch | grep -q -w ${GITHUB_RUN_ID}; then hub pull-request -b master -h ${GITHUB_RUN_ID} --no-edit -m "${GITHUB_REF##*/}-${GITHUB_RUN_ID} Release Update" -m "An automated PR to update access and schema documentation from https://github.com/anzx/salesforce/releases/tag/${GITHUB_REF##*/}-${GITHUB_RUN_ID}"; fi
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
