# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Document

# This workflow will only run on pushes to master , develop and epic/*
on:
  push:
    paths:
      - "force-app/**"
    branches:
      - master

jobs:
  create_documentation:
    runs-on: [self-hosted, salesforce]
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-docs
          token: ${{ secrets.SALESFORCE_DOCS_TOKEN }}

      - name: Checkout doc plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.SALESFORCE_DOC_GEN_TOKEN }}
          path: plugin
          ref: "9c6c8d6"

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: "Install npm packages"
        working-directory: salesforce
        run: |
          mv ci.npmrc .npmrc
          npm ci

      - name: Install plugin
        working-directory: plugin
        shell: bash
        run: yarn install

      # - name: "Create auth files with SFDX_URL secret"
      #   working-directory: salesforce
      #   shell: bash
      #   run: echo ${{ secrets.SALESFORCE_STAGING}} > ./SFDX_URL_STAGING.txt

      - name: "Authenticate all orgs in SFDX CLI"
        working-directory: salesforce
        run: npx sfdx force:auth:sfdxurl:store -a staging --sfdxurlfile=./SFDX_URL_STAGING.txt

      - name: Generate schema and access docs
        working-directory: salesforce
        shell: bash
        run: |
          ../plugin/bin/run doc:schema -f config/doc-def.json -u staging
          ../plugin/bin/run doc:access -f config/doc-def.json -u staging

      - name: Copy docs
        run: |
          rm -rf ./docs/governance/access
          rm -rf ./docs/governance/schema
          mkdir -p ./docs/governance/
          cp -r salesforce/docs/access ./docs/governance/
          cp -r salesforce/docs/schema ./docs/governance/

      - name: Reindex sidebar
        run: |
          npm i lodash@4.17.19
          node reindex

      - name: Create new branch on anzx/salesforce-docs
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${GITHUB_RUN_ID}
          git add docs/static docs/governance sidebars.js
          git commit -m "Update salesforce documentation"
          git push origin ${GITHUB_RUN_ID}

      - name: Create a PR on anzx/salesforce-docs
        shell: bash
        run: |
          if git branch | grep -q -w ${GITHUB_RUN_ID}; then hub pull-request -b master -h ${GITHUB_RUN_ID} --no-edit -m "${GITHUB_REF#refs/heads/}-${GITHUB_RUN_ID} Release Update" -m "An automated PR to update access and schema documentation from https://github.com/anzx/salesforce/releases/tag/${GITHUB_REF#refs/heads/}-${GITHUB_RUN_ID}"; fi
        env:
          GITHUB_TOKEN: ${{ secrets.SALESFORCE_DOCS_TOKEN }}
