# This workflow will export the plauti config
name: Plauti

on:
  workflow_dispatch:

jobs:
  export_config:
    runs-on: [self-hosted, salesforce-prod]

    steps:
      - name: Set BRANCH_NAME
        run: |
          CURRENT_DATE="$(date +%F-%H-%M)"
          echo BRANCH_NAME="plauti-config-${CURRENT_DATE//-}" >> $GITHUB_ENV

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install npm packages
        run: |
          mv ci.npmrc .npmrc
          npm ci -f

      - name: Install plauti
        shell: bash
        run: echo "y" | npx sfdx plugins:install https://artifactory.gcp.anz:443/artifactory/api/npm/npmjs-org/plauti-sfdx/-/plauti-sfdx-0.0.3.tgz

      - name: SFDXURL
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurlbau:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-plauti-anzxbau-np/versions/latest
            sfdxurltest:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-plauti-test-np/versions/latest

      - name: Create auth files with SFDX_URL secrets
        shell: bash
        run: |
          echo ${{ steps.secrets.outputs.sfdxurlbau }} > ./SFDX_URL_PLAUTI_BAU.txt
          echo ${{ steps.secrets.outputs.sfdxurltest }} > ./SFDX_URL_PLAUTI_TEST.txt

      - name: Authenticate BAU and Test orgs in SFDX CLI
        run: |
          npx sfdx force:auth:sfdxurl:store -a plautiTEST --sfdxurlfile=./SFDX_URL_PLAUTI_TEST.txt
          npx sfdx force:auth:sfdxurl:store -a plautiBAU --sfdxurlfile=./SFDX_URL_PLAUTI_BAU.txt

      - name: Run plauti
        run: |
          rm -rf config/duplicate-management-config
          mkdir config/duplicate-management-config
          touch config/duplicate-management-config/duplicate-management-config-bau.json
          touch config/duplicate-management-config/duplicate-management-config-test.json
          npx sfdx plauti:duplicatecheck:config:export --targetusername plautiBAU --file config/duplicate-management-config/duplicate-management-config-bau.json
          npx sfdx plauti:duplicatecheck:config:export --targetusername plautiTEST --file config/duplicate-management-config/duplicate-management-config-test.json

      - name: Create new branch on salesforce and commit plauti config file
        shell: bash
        run: |
          BRANCH_NAME=${{ env.BRANCH_NAME }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          git checkout -b $BRANCH_NAME
          git add config/duplicate-management-config
          git commit -m "Update plauti config file | Test & BAU sandboxes"
          git push origin $BRANCH_NAME

      - name: Link to PR
        run: |
          BRANCH_NAME=${{ env.BRANCH_NAME }}
          echo "https://github.com/anzx/salesforce/compare/$BRANCH_NAME"
