# This workflow deploys changes to a Salesforce project to a Salesforce org with the check only flag
name: Verify

# This workflow will only run on Pull Reqeusts against master , develop and epic/*
on:
  pull_request:
    branches:
      - "master"
      - "develop"
      - "release"
      - "epic/*"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  # This job only does the validation, even though it reads as build_and_deploy. This is due to a name mismatch in terraform.
  build_and_deploy:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Read Harness API Key
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            harness-api-key:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-harness-np/versions/1

      - name: Trigger Harness Job
        uses: docker://anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:latest
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
          DRAFT_PR: ${{ github.event.pull_request.draft }}
          REPO_NAME: ${{ github.event.repository.name }}
          UPLOAD_ARTIFACT: ${{ !github.event.pull_request.draft }}
          RUN_SPECIFIED_TESTS_LABEL: ${{ contains( toJson(github.event.pull_request.labels), 'Run Specified Tests') }}
        with:
          application-name: salesforce
          harness-api-key-plaintext: ${{ steps.secrets.outputs.harness-api-key}}
          target-name: salesforce-ci-np
          target-type: WORKFLOW
          variables: "GITHUB_BASE_REF=${{ env.GITHUB_BASE_REF }};GITHUB_REF=${{ env.GITHUB_REF }};UPLOAD_ARTIFACT=${{ env.UPLOAD_ARTIFACT }};DRAFT_PR=${{ env.DRAFT_PR }};RUN_SPECIFIED_TESTS=${{ env.RUN_SPECIFIED_TESTS_LABEL }};REPO_NAME=${{ env.REPO_NAME }}"
          wait: True

      - if: success()
        name: Code Coverage
        uses: docker://anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:latest
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
          REPO_NAME: ${{ github.event.repository.name }}
        with:
          application-name: salesforce
          harness-api-key-plaintext: ${{ steps.secrets.outputs.harness-api-key}}
          target-name: salesforce-code-coverage-np
          target-type: WORKFLOW
          variables: "GITHUB_BASE_REF=${{ env.GITHUB_BASE_REF }};GITHUB_REF=${{ env.GITHUB_REF }};REPO_NAME=${{ env.REPO_NAME }}"
          wait: True
