# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Deploy
# This workflow will only run on pushes to master , develop and epic/*
on:
  push:
    branches:
      - "develop"
      - "epic/*"

jobs:
  harness-deploy:
    runs-on: [self-hosted, salesforce]
    steps:
      - name: Set BASE_REF
        run: echo BASE_REF=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV
      - name: Trigger Harness Job
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          docker run --rm \
            anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:ede3323 \
            --harness-api-key=CiUALvObyFFSMIO9lC8YUwdvtU6X9/W2dq5AtNmcdgjPME4s6z48ErYBAPO28TLr1ZTTpb/DjiyYN2gj/Ta3b58qEbtlWRKPW69xbx4+2/Bwt84iol8Hbf688qjPZ3i5wa4t025jlfP6EG3um//xpOsssZ9TCYkkqMvtdupzMqxbiOO8uu35eQnesfZKVc05xWVcz5DKpMrLeKe7R7Tsw2yaLHrlhPzwmfp9Gary1D75zhHl59d32udkZyeROJ49naqS6LvOJwx/IV6pfj05zE11U0P2euCBFH18KWP5wRk= \
            --kms-key=projects/anz-x-services-platdev-fcf8c0/locations/global/keyRings/developer-experience/cryptoKeys/anz-x-services-platdev-fcf8c0_github-runner-common-secrets \
            --application-name=salesforce \
            --target-name=salesforce-cd-np \
            --target-type=WORKFLOW \
            --variables='GITHUB_BASE_REF=${{ env.BASE_REF }};GITHUB_REF=${{ env.GITHUB_REF }}' \
            --wait

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Tag Release"
        shell: bash
        run: |
          echo "${GITHUB_REF#refs/heads/}-${GITHUB_RUN_ID}"
          TAG="${GITHUB_REF#refs/heads/}-${GITHUB_RUN_ID}"
          git tag "$TAG"
          git push origin "$TAG"
