# This workflow will trigger the sandbox workflow on harness
name: Sanbox Creation

on:
  push:
    branches: [epic/anzx-bau]
    paths: [config/sandbox-config]

jobs:
  harness-sandbox:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Read Harness API Key
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            harness-api-key:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-harness-np/versions/1

      - name: Trigger Harness Job
        uses: docker://anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:latest
        with:
          application-name: salesforce
          harness-api-key-plaintext: ${{ steps.secrets.outputs.harness-api-key}}
          target-name: salesforce-sandbox-np
          target-type: WORKFLOW
          variables: ""
          wait: TRUE

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Tag new Sandbox"
        shell: bash
        run: |
          echo "sandbox-${GITHUB_RUN_ID}"
          TAG="sandbox-${GITHUB_RUN_ID}"
          git tag "$TAG"
          git push origin "$TAG"
