# This workflow runs JEST tests before deploying changes to a Salesforce project to a Salesforce org
name: Unit Tests

# This workflow will only run on Pull Requests against master , develop and epic/*
on:
  pull_request:
    branches: [develop, master, epic/*]

jobs:
  jest:
    runs-on: [self-hosted, salesforce-prod]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Install npm packages"
        run: |
          mv ci.npmrc .npmrc
          npm ci -f

      - name: Running JEST tests for LWC
        run: npx jest --coverage
