name: Lead Engineers Approval

on:
  pull_request:
    branches: [master, develop, release]
    types: [opened, reopened, synchronize, review_requested, review]

permissions:
  contents: "write"
  id-token: "write"
  pull-requests: "write"

jobs:
  check-approval:
    runs-on: anzx-default
    env:
      LEAD_ENGINEERS: "dawsond1x,patelsu,chiranjeebdhar,sebastienquinternet-anz,murugem4,jasmine-anzx,pvictoriano,victor-wang-anz"
    steps:
      - name: Checkout Salesforce Repository
        uses: actions/checkout@v3

      - name: Install GH
        uses: "anzx/github-reusable-actions/setup-gh-cli@main"
        with:
          gh-cli-version: "2.50.0"

      - name: Authenticate to Github
        env:
          GITHUB_TOKEN: ${{ secrets.SALESFORCE_CXFLOW_GH_TOKEN }}
        run: gh auth setup-git

      - name: Get approved reviewers from PR
        id: pr-reviewers
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          echo "PR Number: $pr_number"

          approved=$(gh pr view $pr_number --json reviews --jq '.reviews[] | select(.state=="APPROVED") | .author.login' | sort | uniq)
          echo "Approved Reviewers:"
          echo "$approved"

          approved_list=$(echo "$approved" | paste -sd, -)
          echo "approved_list=$approved_list" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.SALESFORCE_CXFLOW_GH_TOKEN }}

      - name: Check Lead Engineer Approval
        run: |
          approved_list="${{ steps.pr-reviewers.outputs.approved_list }}"
          lead_engineers="${{ env.LEAD_ENGINEERS }}"

          IFS=',' read -r -a approved_array <<< "$approved_list"
          IFS=',' read -r -a lead_engineers_array <<< "$lead_engineers"

          approved_by_lead_engineer=false

          for reviewer in "${approved_array[@]}"; do
            for member in "${lead_engineers_array[@]}"; do
              if [[ "$reviewer" == "$member" ]]; then
                approved_by_lead_engineer=true
                break 2
              fi
            done
          done

          if [[ "$approved_by_lead_engineer" == true ]]; then
            echo "Lead Engineer approved the PR..."
          else
            echo "No Approvals from Lead Enginners..."
            exit 1
          fi
