# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Lint

# This workflow will only run on Pull Requests against master , develop and epic/*
on:
  pull_request:
    branches: [develop, master, epic/*]

jobs:
  prettier:
    runs-on: [self-hosted, salesforce]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install npm packages"
        run: |
          mv ci.npmrc .npmrc
          npm ci

      - name: "Enforce Style Guidelines"
        shell: bash
        run: |
          npx prettier --write .prettierrc --plugin=prettier-plugin-apex
          echo "Checking Trigger and Class files"
          npx prettier -c force-app/main/default/**/*.{trigger,cls} --parser apex --with-node-modules
          echo "Checking Lightning Web Components"
          npx prettier -c force-app/main/default/lwc/**/*.{js,html,css}
          echo "Checking Aura Components"
          npx prettier -c force-app/main/default/aura/**/*.{js,css,cmp}

  eslint:
    runs-on: [self-hosted, salesforce]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set npm repository mirror"
        run: npm config set registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/

      - name: "Install NPM Packages"
        run: npm ci

      - name: "Lint LWC"
        shell: bash
        run: |
          echo "Linting Lightning Web Components"
          npx eslint force-app/main/default/lwc/**/*.js -c .lwc-eslintrc.json

  xml-lint:
    runs-on: [self-hosted, salesforce]
    env:
      PIP_INDEX_URL: "https://artifactory.gcp.anz/artifactory/api/pypi/pypi/simple"
      LINT_JOB: "YES"
      BASE_BRANCH: ${{ github.base_ref }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Check Changed Files"
        id: check_changed_files
        shell: pwsh
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { $_ -match '.xml$' }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=run_linter::$HasDiff"

      - name: "Get Changed Files"
        id: get_changed_files
        if: steps.check_changed_files.outputs.run_linter == 'True'
        shell: bash
        run: |
          git fetch --tags 
          ci/package.sh

      - name: "Checkout Python"
        if: steps.check_changed_files.outputs.run_linter == 'True'
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.9

      - name: Install Dependencies
        run: python3 -m pip install lxml

      - name: "Checking XML Files"
        if: steps.check_changed_files.outputs.run_linter == 'True'
        run: |
          echo "Linting XML files in diff"
          python ci/xml_linter.py
