# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Lint

# This workflow will only run on Pull Requests against develop
on:
  pull_request:
    branches: [develop, master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install NPM Packages"
        run: npm i --only=dev

      - name: "Enforce Style Guidelines"
        shell: bash
        run: |
          npx prettier --write .prettierrc --plugin=prettier-plugin-apex
          echo "Checking Trigger and Class files"
          npx prettier -c force-app/main/default/**/*.{trigger,cls} --parser apex --with-node-modules
          echo "Checking Lightning Web Components"
          npx prettier -c force-app/main/default/lwc/**/*.{js,html,css}
          echo "Checking Aura Components"
          npx prettier -c force-app/main/default/aura/**/*.{js,css,cmp}
          echo "Checking WebdriverIO project files"
          npx prettier -c webdriverIO/**/*.{ts,js}

  eslint:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install NPM Packages"
        run: |
          npm i --only=dev
          npm i lodash

      - name: "Lint LWC and TypeScript files"
        shell: bash
        run: |
          echo "Linting Lightning Web Components"
          npx eslint force-app/main/default/lwc/**/*.js -c .lwc-eslintrc.json
          echo "Linting TypeScript files"
          npx eslint webdriverIO/**/*.ts -c .ts-eslintrc.json
