# This workflow deploys changes to a Salesforce project to a Salesforce org
name: Deploy

# This workflow will only trigger when manually invoked on epic/cmos-bau or epic/cmos-r2 branches
# See: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest
    outputs:
      is_valid: ${{ steps.isValid.outputs.is_valid }}
      
    steps:
      - name: Set Branch Name
        run: echo BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV
      - id: isValid
        name: determine if valid
        run: |
          if [[ ${{ env.BRANCH_NAME }} == 'epic/cmos-bau' || ${{ env.BRANCH_NAME }} == 'epic/cmos-r2' ]]; then echo ::set-output name=is_valid::$(echo "valid"); else echo ::set-output name=is_valid::$(echo "invalid"); fi

  build_and_deploy:
    needs: [prepare]
    if: needs.prepare.outputs.is_valid == 'valid'
    runs-on: ubuntu-latest
    container: ddawson235/sfdx:latest
    steps:
      - name: Set Branch Name
        run: echo BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV
      - name: Set Sandbox Name
        run: |
          if [ ${{ env.BRANCH_NAME }} == 'epic/cmos-r2' ]; then echo SANDBOX_NAME=$(echo CMOSQA) >> $GITHUB_ENV; else echo SANDBOX_NAME=$(echo CMOSBAUQA) >> $GITHUB_ENV; fi
      - name: "Authenticate the org"
        shell: bash
        run: |
          echo ${{ env.SANDBOX_NAME }}
          echo ${{ secrets[env.SANDBOX_NAME] }} > ./SFDX_URL_${{ env.SANDBOX_NAME }}.txt
          sfdx force:auth:sfdxurl:store -a ${{ env.SANDBOX_NAME }} --sfdxurlfile=./SFDX_URL_${{ env.SANDBOX_NAME }}.txt
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Generate package"
        id: package
        shell: bash
        run: |
          git fetch --tags 
          ci/package.sh
        env:
          TAG_PREFIX: ${{ env.SANDBOX_NAME }}
          SOURCE_BRANCH: ${{ env.BRANCH_NAME }}

      - uses: actions/upload-artifact@v1
        if: ${{ steps.package.outputs.ARTEFACT_GENERATED }}
        with:
          name: package
          path: ./artefact/

      - name: "Deploy Changes"
        shell: bash
        run: ci/deploy.sh
        env:
          DEPLOY_ROOT: ./artefact/
          BUILD_COMMAND: deploy
          ORG_NAME: ${{ env.SANDBOX_NAME }}

      - name: "Tag Release"
        shell: bash
        run: |
          TAG="${{ env.SANDBOX_NAME }}-${GITHUB_RUN_ID}"
          echo "$TAG"
          git tag "$TAG"
          git push origin "$TAG"
