name: Add PR Merge Reminder
on:
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Add Comment Reminder"
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }} here's a reminder for merging PR's:

            | Squash &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |     |         |
            | ------- | --- | ------- |
            | feature | ➡️  | epic    |
            | feature | ➡️  | develop |
            | feature | ➡️  | master  |
            | epic **   | ➡️  | develop |

            | Merge Commit |     |         |
            | ------------ | --- | ------- |
            | develop      | ➡️  | epic    |
            | develop      | ➡️  | master  |
            | master       | ➡️  | develop |

            ** *epic branch can be squashed into release except in scenario where epic/x contains multiple epics*
