name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "Release Name"
        required: true
        type: string

permissions:
  contents: "write"
  id-token: "write"

jobs:
  Release:
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:1.2.4"
      options: --user root
      volumes:
        - ${{ github.workspace }}/release:/opt/harness-delegate/release
    runs-on: anzx-default
    concurrency:
      group: "salesforce-release-${{ github.event.inputs.NAME }}"
      cancel-in-progress: false
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        config:
          - DEPLOYMENT_ENVIRONMENT: "prod-release-start"
            DEPLOYMENT_TITLE: "Stage 1: Preprod Deployment"

          - DEPLOYMENT_ENVIRONMENT: "prod-validation"
            DEPLOYMENT_TITLE: "Stage 2: Prod Validation"

          - DEPLOYMENT_ENVIRONMENT: "prod-deployment"
            DEPLOYMENT_TITLE: "Stage 3: Prod Deployment"

    environment: "${{ matrix.config.DEPLOYMENT_ENVIRONMENT }}"
    env:
      RELEASE_NAME: "${{ github.event.inputs.NAME }}"
      ARTIFACTORY_SECRET_NAME: "h-salesforce-prod-artifact"
      PREPROD_SECRET_NAME: "h-salesforce-prod-preprod"
      PROD_CONSUMER_KEY_SECRET_NAME: "h-salesforce-prod-ca-consumerkey"
      PROD_CERT_SECRET_NAME: "h-salesforce-prod-cert"
      PREPROD_DEPLOYMENT_STEP: ${{ matrix.config.DEPLOYMENT_ENVIRONMENT == 'prod-release-start' }}
      PROD_VALIDATION_STEP: ${{ matrix.config.DEPLOYMENT_ENVIRONMENT == 'prod-validation' }}
      PROD_DEPLOYMENT_STEP: ${{ matrix.config.DEPLOYMENT_ENVIRONMENT == 'prod-deployment' }}
      STAGE_NAME: ${{ matrix.config.DEPLOYMENT_ENVIRONMENT }}
      REPO_NAME: ${{ github.event.repository.name }}
      PROD_DEPLOY_USERNAME: "tech.gcb@anzx.com"
      PROD_URL: "https://anz.my.salesforce.com"

    steps:
      - name: Environment Varibales Debug
        run: |
          echo "DEBUG: PREPROD_DEPLOYMENT_STEP=${{ env.PREPROD_DEPLOYMENT_STEP }}"
          echo "DEBUG: PROD_VALIDATION_STEP=${{ env.PROD_VALIDATION_STEP }}"
          echo "DEBUG: PROD_DEPLOYMENT_STEP=${{ env.PROD_DEPLOYMENT_STEP }}"
          echo "DEBUG: STAGE_NAME=${{ env.STAGE_NAME }}"
          echo "DEBUG: REPO_NAME=${{ env.REPO_NAME }}"

      - name: Link SGD plugin
        run: |
          cd /opt/harness-delegate/.local/share/sf
          sf plugins:link node_modules/sfdx-git-delta/bin

      - name: NPM package Version | node, sfdx, sf, sgd version
        run: |
          echo "node version: $(node -v)"
          echo "sf version: $(sf -v)"
          echo "sf plugins: $(sf plugins)"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "OIDC Authentication (Salesforce Harness Delegate Service Account)"
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-prod@anz-x-bootstrap-prod-3b7a6d.iam.gserviceaccount.com"

      - name: "Retrieve GSM Credentials"
        id: secrets
        uses: "google-github-actions/get-secretmanager-secrets@v1"
        with:
          secrets: |-
            preprod:projects/810679854929/secrets/${{ env.PREPROD_SECRET_NAME }}/versions/latest
            prod-consumer-key:projects/810679854929/secrets/${{ env.PROD_CONSUMER_KEY_SECRET_NAME }}/versions/latest
            prod-cert:projects/810679854929/secrets/${{ env.PROD_CERT_SECRET_NAME }}/versions/latest
            artifactory:projects/810679854929/secrets/${{ env.ARTIFACTORY_SECRET_NAME }}/versions/latest
      - name: Add Genral Secrets to ENV
        run: |
          echo CLEANING_JOB="false" >> $GITHUB_ENV
          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV
          lastTag="$( git describe --abbrev=0 --tags --match master* )"
          echo BASE_REF_LAST_TAG="$lastTag" >> $GITHUB_ENV

      - name: Run ${{ matrix.config.DEPLOYMENT_ENVIRONMENT }}
        run: |
          node --no-warnings ci/workflows/Orchestrations/release.mjs "${{ steps.secrets.outputs.preprod }}" "${{ steps.secrets.outputs.prod-consumer-key }}" "${{ steps.secrets.outputs.prod-cert }}" "${{ steps.secrets.outputs.artifactory }}"
          echo CLEANING_JOB="true" >> $GITHUB_ENV

      - name: Cleaning | Create Tag
        run: |
          node --no-warnings ci/workflows/Orchestrations/release.mjs "${{ steps.secrets.outputs.preprod }}" "${{ steps.secrets.outputs.prod-consumer-key }}" "${{ steps.secrets.outputs.prod-cert }}" "${{ steps.secrets.outputs.artifactory }}"

  Cleanup:
    name: "Cleanup"
    runs-on: anzx-default
    needs: [Release]
    if: failure() || always()
    steps:
      - name: Cleanup build artifacts
        id: cleanup
        run: |
          if [ -d "${{ github.workspace }}/release" ]; then
            rm -rf "${{ github.workspace }}/release"
          fi

  upload_bq_prod_schema_changes:
    uses: ./.github/workflows/bq-upload-object-changes.yaml
    needs: [Release]
    secrets: inherit
    with:
      prod_deployment: true
