name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "Release Name"
        required: true
        type: string
      CHANGE_REQUEST_RECORD:
        description: "Change Request Name"
        required: false
        type: string
      CHANGE_REQUEST_URL:
        description: "Change Request URL"
        required: false
        type: string

permissions:
  contents: "write"
  id-token: "write"

jobs:
  Preprod-Deployment:
    uses: ./.github/workflows/_release.yml
    with:
      DEPLOYMENT_ENVIRONMENT: "prod-release-start"
      DEPLOYMENT_TITLE: "Stage 1: Preprod Deployment"
      PUBLISH_EVENT_ENV_NAME: "preprod"
      JOB_NAME: "preprod-deployment"
      RELEASE_NAME: "${{ github.event.inputs.NAME }}"
    secrets:
      token: ${{ secrets.SALESFORCE_PROD_CHECKOUT_TOKEN }}

  Prod-Validation:
    needs: [Preprod-Deployment]
    uses: ./.github/workflows/_release.yml
    with:
      DEPLOYMENT_ENVIRONMENT: "prod-validation"
      DEPLOYMENT_TITLE: "Stage 2: Prod Validation"
      PUBLISH_EVENT_ENV_NAME: ""
      JOB_NAME: "prod-validation"
      RELEASE_NAME: "${{ github.event.inputs.NAME }}"
    secrets:
      token: ${{ secrets.SALESFORCE_PROD_CHECKOUT_TOKEN }}

  Prod-Deployment:
    needs: [Prod-Validation]
    uses: ./.github/workflows/_release.yml
    with:
      DEPLOYMENT_ENVIRONMENT: "prod-deployment"
      DEPLOYMENT_TITLE: "Stage 3: Prod Deployment"
      PUBLISH_EVENT_ENV_NAME: "prod"
      JOB_NAME: "prod-deployment"
      RELEASE_NAME: "${{ github.event.inputs.NAME }}"
      JOB_ID_FILE_NAME_INPUT: ${{ needs.Prod-Validation.outputs.JOB_ID_FILE_NAME }}
    secrets:
      token: ${{ secrets.SALESFORCE_PROD_CHECKOUT_TOKEN }}

  Cleanup:
    name: "Cleanup"
    runs-on: anzx-default
    needs: [Preprod-Deployment, Prod-Validation, Prod-Deployment]
    if: always()
    steps:
      - name: Cleanup build artifacts
        id: cleanup
        run: |
          if [ -d "${{ github.workspace }}/release" ]; then
            rm -rf "${{ github.workspace }}/release"
          fi

  update-sdva:
    runs-on: anzx-default
    needs: [Preprod-Deployment]
    outputs:
      last_tag: ${{ steps.info.outputs.last_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest master tag
        id: info
        run: |
          lastTag="$( git describe --abbrev=0 --tags --match 'master*' )"
          echo "Last tag: $lastTag"
          echo "last_tag=$lastTag" >> $GITHUB_OUTPUT

      - name: update-plat-app-versions
        if: ${{ success() }}
        uses: anzx/sec-domain-actions/publish-app-scm-version@main
        with:
          repo: ${{ github.repository }}
          asset: salesforce
          component: salesforce
          env: prod
          release-tag-or-sha: ${{ steps.info.outputs.last_tag }}
          use-gh-token-vending: true
          app-repo-token: ${{ secrets.GITHUB_TOKEN }}

  prepare-notification:
    runs-on: anzx-default
    needs: [Prod-Deployment]
    environment: "prod-validation"
    env:
      CHANGE_REQUEST_URL: "${{ github.event.inputs.CHANGE_REQUEST_URL }}"
      CHANGE_REQUEST_NUMBER: "${{ github.event.inputs.CHANGE_REQUEST_RECORD }}"
      RELEASE_NAME: "${{ github.event.inputs.NAME }}"
      REPO_NAME: "${{ github.event.repository.name }}"
      RELEASE_PIPELINE: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    outputs:
      slack_msg: ${{ steps.set-msg.outputs.slack_msg}}
    steps:
      - name: Conditional Checkout
        if: ${{ env.CHANGE_REQUEST_URL == '' || env.CHANGE_REQUEST_NUMBER == '' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Slack Message
        id: set-msg
        run: |
          CAPITALIZED_REPO_NAME=$(echo "${{ env.REPO_NAME }}" | awk '{print toupper(substr($0,1,1)) substr($0,2)}') 
          if [[ -z "${{ env.CHANGE_REQUEST_URL }}" ]] || [[ -z "${{ env.CHANGE_REQUEST_NUMBER }}" ]];then
            lastTag="$( git describe --abbrev=0 --tags --match 'master*' )"
            RELEASE_VERSION="https://github.com/${{ github.repository }}/tree/$lastTag"
            msg="*☁️ $CAPITALIZED_REPO_NAME Release*\\n*Release*: ${{ env.RELEASE_NAME }}\\n*Release Version*: $RELEASE_VERSION\\n*Release Pipeline*: ${{ env.RELEASE_PIPELINE }}"
          else
            msg="*☁️ $CAPITALIZED_REPO_NAME Release*\\n*Release*: ${{ env.RELEASE_NAME }}\\n*Change Request*: <${{ env.CHANGE_REQUEST_URL }}|${{ env.CHANGE_REQUEST_NUMBER }}>\\n*Release Pipeline*: ${{ env.RELEASE_PIPELINE }}"
          fi
          echo "slack_msg=$msg" >> "$GITHUB_OUTPUT"

  send-release-notification:
    needs: [Prod-Deployment, prepare-notification]
    uses: anzx/github-reusable-workflows/.github/workflows/notification-hub.yaml@main
    with:
      isSlack: true
      slackChannels: prod-release-notifications
      slackMessage: "${{ needs.prepare-notification.outputs.slack_msg }}"
      slackPrivate: true
