name: Salesforce Run All Local Tests

on:
  pull_request:
    branches:
      - "master"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: "read"
  id-token: "write"

jobs:
  run-all-tests:
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:1.2.3"
      options: --user root
    runs-on: [self-hosted, cd-ubuntu-s-np]
    steps:
      - name: NPM package Version | node, sfdx, sf, sgd version
        run: |
          echo "node version: $(node -v)"
          echo "sf version: $(sf -v)"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: ENV vars
        run: |
          echo BASE_REF="${{ github.base_ref }}" >> $GITHUB_ENV
          echo PR_NUMBER="${{ github.event.number }}" >> $GITHUB_ENV
          echo REPO_NAME="${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV

      - name: Find Proper TargetOrg and Secret Name
        run: |
          secretName=$( node ci/workflows/Orchestrations/runAllTests.mjs )
          echo "$secretName"
          echo SECRET_NAME="$secretName" >> $GITHUB_ENV
          echo ARTIFACTORY_SECRET_NAME="h-salesforce-np-artifact" >> $GITHUB_ENV
          echo WHICH_JOB="runAllTests" >> $GITHUB_ENV

      - name: Find GSM credential
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/448406129405/secrets/${{ env.SECRET_NAME }}/versions/latest
            artifactory:projects/448406129405/secrets/${{ env.ARTIFACTORY_SECRET_NAME }}/versions/latest
            proxypass:projects/anz-x-bootstrap-np-487e09/secrets/h-salesforce-np-proxy-password/versions/3

      - name: Setup HTTP Proxy
        id: "proxy-harness-delegate"
        uses: "anzx/github-reusable-actions/setup-http-proxy@main"
        with:
          production: false
          proxy-username: "sf-harness-delegate-np"
          proxy-password: "${{ steps.secrets.outputs.proxypass }}"

      - name: Run all tests
        run: |
          node ci/workflows/Orchestrations/runAllTests.mjs "${{ steps.secrets.outputs.sfdxurl }}" "${{ steps.secrets.outputs.artifactory }}"
          echo WHICH_JOB="clean" >> $GITHUB_ENV

      - name: Cleaning
        run: |
          node ci/workflows/Orchestrations/runAllTests.mjs
