name: Salesforce Run All Local Tests

on:
  pull_request:
    branches:
      - "master"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: "read"
  id-token: "write"

jobs:
  run-all-tests:
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:1.2.1"
      options: --user root
    runs-on: anzx-default
    steps:
      - name: NPM package Version | node, sfdx, sf, sgd version
        run: |
          echo "node version: $(node -v)"
          echo "sf version: $(sf -v)"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: ENV vars
        run: |
          echo BASE_REF="${{ github.base_ref }}" >> $GITHUB_ENV
          echo PR_NUMBER="${{ github.event.number }}" >> $GITHUB_ENV
          echo REPO_NAME="${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV

      - name: Find Proper TargetOrg and Secret Name
        run: |
          secretName=$( node ci/workflows/Orchestrations/runAllTests.mjs )
          projectId=anz-x-bootstrap-np-487e09

          if [[ "$secretName" == "sf-platform-np-"* ]];then
            projectId=anz-x-gh-sf-nonprod-ea5caa
          fi

          echo "$secretName"
          echo SECRET_NAME="$secretName" >> $GITHUB_ENV
          echo PROJECT_ID="$projectId" >> $GITHUB_ENV
          echo ARTIFACTORY_SECRET_NAME="sf-platform-np-artifact" >> $GITHUB_ENV
          echo WHICH_JOB="runAllTests" >> $GITHUB_ENV

      - name: Find GSM credential
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/${{ env.PROJECT_ID }}/secrets/${{ env.SECRET_NAME }}/versions/latest
            artifactory:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/${{ env.ARTIFACTORY_SECRET_NAME }}/versions/latest

      - name: Run all tests
        run: |
          node ci/workflows/Orchestrations/runAllTests.mjs "${{ steps.secrets.outputs.sfdxurl }}" "${{ steps.secrets.outputs.artifactory }}"
          echo WHICH_JOB="clean" >> $GITHUB_ENV

      - name: Cleaning
        run: |
          node ci/workflows/Orchestrations/runAllTests.mjs
