name: Salesforce Run All Local Tests

on:
  pull_request:
    branches:
      - "master"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  workflow_dispatch:
    inputs:
      BASE_REF:
        description: "baseRef to create the report"
        required: true
        type: string
      JOB_ID:
        description: "Last Validation Job Id (Optional)"
        required: false
        type: string

permissions:
  contents: "read"
  id-token: "write"

concurrency:
  group: "run-all-tests-${{ github.event.repository.name }}-${{ github.event.inputs.BASE_REF }}-${{ github.event.inputs.JOB_ID }}"
  cancel-in-progress: true

jobs:
  run-all-tests:
    container:
      image: "salesforce-docker.artifactory.gcp.anz/salesforce-delegate:2.1.0"
      options: --user root
    runs-on: anzx-default
    env:
      GITHUB_EVENT: ${{ github.event_name }}
      INPUTS_JOB_ID: ${{ github.event.inputs.JOB_ID }}
      PR_NUMBER: ${{ github.event.number }}
      REPO_NAME: ${{ github.event.repository.name }}
      BASE_REF: ${{ github.event_name == 'pull_request' && 'develop' || github.event.inputs.BASE_REF }}
      WHICH_JOB: "runAllTests"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: OIDC Authentication (Salesforce Harness Delegate Service Account)
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: Prepare ENV vars
        run: |
          secretName=$( node ci/workflows/Orchestrations/findSecret.mjs )
          echo "$secretName"

          echo WORKING_DIR="$(pwd)" >> $GITHUB_ENV
          echo SECRET_NAME="$secretName" >> $GITHUB_ENV
          echo WHICH_JOB="runAllTests" >> $GITHUB_ENV

      - name: Find GSM credential
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/${{ env.SECRET_NAME }}/versions/latest
            artifactory:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/sf-platform-np-artifact/versions/latest

      - name: Run all tests
        run: |
          if [[ "${{ env.GITHUB_EVENT }}" != 'workflow_dispatch' ]] || [[ "${{ env.GITHUB_EVENT }}" == 'workflow_dispatch' && "${{ env.INPUTS_JOB_ID }}" == '' ]];then
            node ci/workflows/Orchestrations/runAllTests.mjs "${{ steps.secrets.outputs.sfdxurl }}" "${{ steps.secrets.outputs.artifactory }}"
          fi

          if [[ "${{ env.GITHUB_EVENT }}" == 'workflow_dispatch' ]];then
            echo WHICH_JOB="prepareTestReport" >> $GITHUB_ENV
          else
            echo WHICH_JOB="clean" >> $GITHUB_ENV
          fi

      - name: Report Summary
        if: ${{ env.WHICH_JOB == 'prepareTestReport' }}
        run: |
          node ci/workflows/Orchestrations/runAllTests.mjs "${{ steps.secrets.outputs.sfdxurl }}" "${{ steps.secrets.outputs.artifactory }}"
          echo WHICH_JOB="clean" >> $GITHUB_ENV

      - name: Cleaning
        run: |
          node ci/workflows/Orchestrations/runAllTests.mjs
