# This is a caller workflow to manage Salesforce Validation & Deployment jobs
name: Salesforce Validation/Deployment

on:
  pull_request:
    branches:
      - "master"
      - "develop"
      - "release"
      - "epic/*"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - closed

permissions:
  contents: write
  id-token: write

jobs:
  validation-run:
    if: ${{ github.event.action != 'closed' }}
    uses: ./.github/workflows/_validation.yml

  validation:
    if: ${{ success() }}
    runs-on: [self-hosted, salesforce-prod]
    needs: [validation-run]
    steps:
      - name: Check Validation Status
        run: echo "Validation Run Successfully"

  validation-intpnv-sandbox:
    if: ${{ (github.base_ref == 'master') && (github.event.pull_request.merged == true) }}
    uses: ./.github/workflows/_validation.yml
    with:
      sfdx_name: "h-salesforce-np-intpnv"

  quick-deploy-intpnv-sandbox:
    if: ${{ github.event.pull_request.merged == true }}
    needs: [validation-intpnv-sandbox]
    uses: ./.github/workflows/_quick-deployment.yml
    with:
      sfdx_name: "h-salesforce-np-intpnv"
