# This is a caller workflow to manage Salesforce Validation & Deployment jobs
name: Salesforce Validation/Deployment

on:
  pull_request:
    branches:
      - "master"
      - "develop"
      - "release"
      - "epic/*"
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - closed

permissions:
  contents: write
  id-token: write

concurrency:
  group: "${{ github.run_id }}"
  cancel-in-progress: false

jobs:
  validation-run:
    if: ${{ github.event.action != 'closed' }}
    uses: ./.github/workflows/_validation.yml

  validation:
    if: ${{ always() }}
    runs-on: [self-hosted, salesforce-prod]
    needs: [validation-run]
    steps:
      - if: ${{ (needs.validation-run.result == 'success') || (github.event.pull_request.merged == true) }}
        run: echo "Validation Run Succeed"

      - if: ${{ (needs.validation-run.result != 'success') && (github.event.pull_request.merged != true)}}
        run: |
          echo "Validation Run Failed"
          exit 1

  validation-deployment-different-sandboxes:
    if: ${{ (github.base_ref == 'master') && (github.event.pull_request.merged == true) }}
    strategy:
      fail-fast: false
      matrix:
        secret-name: ["sf-platform-np-intpnv", "sf-platform-np-blm"]
    uses: ./.github/workflows/_validation-quick-deployment.yml
    with:
      sfdx_name: ${{ matrix.secret-name }}
