# This workflow will trigger sandbox pipeline from harness
name: Sandbox

on:
  push:
    branches: [develop]
    paths:
      - config/sandbox-config/*

jobs:
  Sandbox-Creation:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Install node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Checkout Salesforce repo
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Find sandbox Info
        run: |
          if [[ -f ci/new-sandbox-info.sh ]];then
            chmod +x ci/new-sandbox-info.sh
            source ci/new-sandbox-info.sh
          fi
          echo SANDBOX_NAME=$sandboxName >> $GITHUB_ENV
          echo PROD_EMAIL=$email >> $GITHUB_ENV
          echo LICENSE_TYPE=$licenseType >> $GITHUB_ENV

      - name: Read Harness API Key
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            harness-api-key:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-harness-prod/versions/latest

      - name: Trigger Harness Job
        uses: docker://anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:latest
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        with:
          application-name: salesforce
          harness-api-key-plaintext: ${{ steps.secrets.outputs.harness-api-key}}
          target-name: sandbox-creation
          target-type: PIPELINE
          variables: "SANDBOX_NAME=${{ env.SANDBOX_NAME }};PROD_EMAIL=${{ env.PROD_EMAIL }};LICENSE_TYPE=${{ env.LICENSE_TYPE }};REPO_NAME=${{ env.REPO_NAME }}"
          wait: TRUE

      - name: Tag new Sandbox against develop branch
        shell: bash
        run: |
          echo "sandbox-${GITHUB_RUN_ID}"
          TAG="sandbox-${GITHUB_RUN_ID}"
          git tag "$TAG"
          git push origin "$TAG"
