# This workflow will check if a new/updated field has all the metadata information.
name: Security scan

on:
  pull_request:
    branches: [develop, master, epic/*]

jobs:
  security-check:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "16"

      - name: Checkout salesforce repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Security Check Profiles
        run: |
          rm -rf ./tmp
          BRANCH_NAME=${{ github.base_ref }}

          if [[ -f ci/build-security-check.sh ]];then
            chmod +x ci/build-security-check.sh
            source ci/build-security-check.sh "force-app/main/default/profiles" "profiles"
          fi

      - name: Security Check Permission sets
        run: |
          rm -rf ./tmp
          BRANCH_NAME=${{ github.base_ref }}
          if [[ -f ci/build-security-check.sh ]];then
            chmod +x ci/build-security-check.sh
            source ci/build-security-check.sh "force-app/main/default/permissionsets" "permissionsets"
          fi
