name: Code Coverage

on:
  workflow_run:
    workflows: ["Verify"]
    branches: ["develop", "master"]
    types:
      - completed

jobs:
  apex-code-coverage:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - name: Read Harness API Key
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            harness-api-key:projects/36540621485/secrets/ghr-salesforce-prod-salesforce-harness-np/versions/1

      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Code Coverage
        uses: docker://anzx-docker.artifactory.gcp.anz/github-actions-harness-trigger:latest
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
        with:
          application-name: salesforce
          harness-api-key-plaintext: ${{ steps.secrets.outputs.harness-api-key}}
          target-name: salesforce-code-coverage-np
          target-type: WORKFLOW
          variables: "GITHUB_BASE_REF=${{ env.GITHUB_BASE_REF }};GITHUB_REF=${{ env.GITHUB_REF }}"
          wait: True
