# Currently under development. This workflow looks for object changes and uploads them to gcs bucket in sit.
name: Upload Object Changes

on:
  workflow_dispatch:
  push:
    branches:
      - epic/upload-object-changes-workflow
      - feature/object-changes-workflow*

permissions:
  contents: "read"
  id-token: "write"

jobs:
  upload_object_changes:
    runs-on: [anzx-default]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: Checkout doc gen plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.SALESFORCE_DOC_GEN_TOKEN }}
          path: plugin

      - name: Install npm packages
        working-directory: salesforce
        run: |
          mv ci.npmrc .npmrc
          npm ci -f

      - name: Install yarn
        working-directory: plugin
        shell: bash
        run: |
          npm install --global yarn --registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/
          yarn config set registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/
          yarn --version

      - name: Install plugin
        working-directory: plugin
        shell: bash
        run: |
          mv ci.yarnrc .yarnrc
          rm -rf node_modules && yarn install --frozen-lockfile

      - name: "OIDC Authentication (Salesforce Harness Delegate Service Account)"
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: SFDXURL
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/sf-platform-np-test/versions/latest
            artifactory_token:projects/anz-x-gh-sf-nonprod-ea5caa/secrets/sf-platform-np-artifact/versions/latest

      - name: Authenticate all orgs in SFDX CLI
        working-directory: salesforce
        run: echo "${{ steps.secrets.outputs.sfdxurl }}" | npx sf org login sfdx-url -a "${{ github.base_ref }}" --sfdx-url-file=/dev/stdin

      - name: Get objects with new fields and fieldsaccessdiff
        working-directory: salesforce
        id: get-changed-objects
        shell: bash
        run: |
          sfdatasync_object_list=$(jq -r '.sfdatasync_object_whitelist[]' ./config/object-changes-list.json)
          odaseva_object_list=$(jq -r '.odaseva_object_whitelist[]' ./config/object-changes-list.json)

          for object in $sfdatasync_object_list; do
            echo "running fieldsaccessdiff on sfdatasync user for $object..."
            if  ! ../plugin/bin/run doc:fieldsaccessdiff -a sfdatasync.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
                  -f sfdatasync_user_output -u tech.gcb@anzx.com.test24; then
                errors+=("$object for user sfdatasync.user@anzx.com.test24")
            fi
          done
          for object in $sfdatasync_object_list; do
            echo "running fieldsaccessdiff on odaseva user for $object..."
            if  ! ../plugin/bin/run doc:fieldsaccessdiff -a odaseva.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
                  -f odaseva_user_output -u tech.gcb@anzx.com.test24; then
                errors+=("$object for user odaseva.user@anzx.com.test24")
            fi
          done

          if [ ${#errors[@]} -ne 0 ]; then
            echo "Errors occurred with the following objects:"
            for err in "${errors[@]}"; do
                echo "$err"
            done
            exit 1 # Exit with a non-zero status
          fi

      # Upload to artifactory
      - name: Push changes to artifactory
        if: ${{ (steps.get-changed-objects.outcome == 'success' || steps.get-changed-objects.outcome == 'failure') && !cancelled() }}
        working-directory: salesforce
        id: push-to-artifactory
        shell: bash
        run: |
          # zip the files
          mkdir output && mv sfdatasync_user_output odaseva_user_output output/
          ARTIFACT_NAME="sf_objects_diff_develop_$(git rev-parse --verify HEAD)"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

          zip -r $ARTIFACT_NAME output && ls -la
          curl -H "Authorization: Bearer ${{ steps.secrets.outputs.artifactory_token }}" -X PUT -T "$ARTIFACT_NAME.zip" "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$ARTIFACT_NAME.zip"

      # Upload to GCS
      - id: "upload-folder-to-gcs"
        if: ${{ (steps.get-changed-objects.outcome == 'success' && steps.push-to-artifactory.outcome == 'success') && !cancelled() }}
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "${{ github.workspace }}/salesforce/output/"
          destination: "salesforce-sit-github-workflows/upload-object-changes/success_output"
          project_id: anz-x-gh-sf-dev-ef8edd
