# Currently under development. This workflow syncs object changes to gcs buckets.
name: Upload Object Changes

on:
  pull_request:
    # paths:
    #   - "./force-app/main/default/objects/**"
    branches:
      - epic/upload-object-changes-workflow

permissions:
  contents: "read"
  id-token: "write"

jobs:
  create_docs:
    runs-on: [self-hosted, salesforce-prod]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: Checkout doc gen plugin
        uses: actions/checkout@v2
        with:
          repository: anzx/salesforce-doc-gen
          token: ${{ secrets.SALESFORCE_DOC_GEN_TOKEN }}
          path: plugin

      - name: Install npm packages
        working-directory: salesforce
        run: |
          mv ci.npmrc .npmrc
          npm ci -f

      - name: Install yarn
        working-directory: plugin
        shell: bash
        run: |
          npm install --global yarn --registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/
          yarn config set registry https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/

      - name: 🧱 Check yarn version
        working-directory: plugin
        run: yarn --version
        shell: bash

      - name: Install plugin
        working-directory: plugin
        run: |
          mv ci.yarnrc .yarnrc
          rm -rf node_modules && yarn install --frozen-lockfile
        shell: bash

      - name: SFDXURL
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            sfdxurl:projects/36540621485/secrets/sf-platform-prod-preprod/versions/latest
            artifactory_token:projects/anz-x-gha-prod-0f0d8b/secrets/ghr-salesforce-prod-artifactory-password/versions/latest

      # - name: Create auth files with SFDX_URL secret
      #   working-directory: salesforce
      #   shell: bash
      #   run: echo ${{ steps.secrets.outputs.sfdxurl }} > ./SFDX_URL_STAGING.txt

      - name: Authenticate all orgs in SFDX CLI
        working-directory: salesforce
        run: |
          echo "${{ steps.secrets.outputs.sfdxurl }}" | npx sf org login sfdx-url -a "${branchName}" --sfdx-url-file=/dev/stdin

      - name: Get objects with new fields and fieldsaccessdiff
        working-directory: salesforce
        shell: bash
        run: |
          # Get all objects
          directory_path=./force-app/main/default/objects
          changed_objects=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD -- "$directory_path" \
                                | grep '/fields/' | cut -d '/' -f 5 | sort | uniq)
          echo "changed_objects=$changed_objects"

          # run plugin docs:fieldsaccessdiff
          if [ -n "$changed_objects" ]; then
            for object in $changed_objects; do
              ../plugin/bin/run doc:fieldsaccessdiff -a sfdatasync.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
                  -f output --sfdxurlfile=./SFDX_URL_STAGING.txt
            done

            # zip the files
            short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
            zip -r "$short_sha_${{ github.run_id }}" output

            ls -la
          else
            echo "no changed objects found..."
          fi

      #  Login to registry
      - name: "Registry Authentication"
        uses: "docker/login-action@v3"
        with:
          registry: "salesforce-docker.artifactory.gcp.anz"
          username: "robot-salesforce-ci"
          password: "${{ steps.secrets.outputs.artifactory_token }}"

      # upload to artifactory and then gcs
