# Currently under development. This workflow syncs object changes to gcs bucket in non-prod.
name: Validate Object Changes

on:
  workflow_dispatch:
  pull_request:
    branches:
      - epic/upload-object-changes-workflow

permissions:
  contents: "read"
  id-token: "write"

jobs:
  validate_object_changes:
    runs-on: [anzx-default]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"

      - name: Checkout salesforce repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: salesforce

      - name: Pull changes from artifactory
        working-directory: salesforce
        id: pull-from-artifactory
        shell: bash
        run: |
          ARTIFACTORY_ARTIFACT_NAME="sf_objects_diff_develop_${{ github.event.pull_request.head.sha }}"
          echo "ARTIFACTORY_ARTIFACT_NAME=$ARTIFACTORY_ARTIFACT_NAME"

          status_code=$(wget --server-response -P artifactory_success_output/ "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip" 2>&1 | awk '/HTTP\// {print $2}' | tail -n 1)
          if [ "$status_code" -eq 200 ]; then
            unzip artifactory_success_output/$ARTIFACTORY_ARTIFACT_NAME.zip -d artifactory_success_output
          elif [ "$status_code" -eq 404 ]; then
              echo "Error: File not found (Status code: $status_code). This means that the upload-object-changes.yml workflow was not run on ${{ github.sha }} as \
              a post deployment step on the develop branch. If this was a commit for a conflict fix on master, please merge it into develop first and then run the \
              upload-object-changes.yml workflow on the develop branch. You can then re-run this workflow."
              exit 1
          else
              echo "Received HTTP status code when pulling : $status_code"
              exit 1
          fi

      - name: "Set up Cloud SDK"
        uses: "anzx/github-reusable-actions/setup-gcloud@main"
        with:
          install_components: "core"

      - name: "OIDC Authentication (Salesforce Harness Delegate Service Account)"
        id: "authenticate-harness-delegate"
        uses: "anzx/github-reusable-actions/authenticate-gcp@main"
        with:
          service_account: "h-sf-primary-np@anz-x-bootstrap-np-487e09.iam.gserviceaccount.com"

      - name: Pull current changes from GCS
        working-directory: salesforce
        id: pull-from-gcs
        shell: bash
        run: |
          mkdir gcs_success_output && ls -la
          gcloud storage cp -r --project anz-x-gh-sf-sit-4e60a7 gs://salesforce-sit-github-workflows/upload-object-changes/success_output gcs_success_output

      - name: Run diff
        working-directory: salesforce
        id: run-diff
        shell: bash
        run: |
          odaseva_sha_object_fields="artifactory_success_output/output/odaseva_user_output/fieldsaccessdiff"
          odaseva_gcs_object_fields="gcs_success_output/success_output/output/odaseva_user_output/fieldsaccessdiff"
          sfdatasync_sha_object_fields="artifactory_success_output/output/sfdatasync_user_output/fieldsaccessdiff"
          sfdatasync_gcs_object_fields="gcs_success_output/success_output/output/sfdatasync_user_output/fieldsaccessdiff"

          CHANGES_DETECTED=FALSE

          diff_output=$(diff -qr "$odaseva_sha_object_fields" "$odaseva_gcs_object_fields")
          echo "$diff_output\n"
          if [ -n "$diff_output" ]; then
              echo "Changes found between $odaseva_sha_object_fields and $odaseva_gcs_object_fields...\n"
              echo "Uploading odaseva_sha_object_fields..."
              CHANGES_DETECTED=TRUE
          else
              echo "No changes found. Moving on..."
          fi

          diff_output=$(diff -qr "$sfdatasync_sha_object_fields" "$sfdatasync_gcs_object_fields")
          echo "$diff_output\n"
          if [ -n "$diff_output" ]; then
              echo "Changes found between $sfdatasync_sha_object_fields and $sfdatasync_gcs_object_fields...\n"
              echo "Uploading sfdatasync_sha_object_fields..."
              CHANGES_DETECTED=TRUE
          else
              echo "No changes found. Moving on..."
          fi

          echo "CHANGES_DETECTED=$CHANGES_DETECTED" >> $GITHUB_OUTPUT

      # Upload to GCS
      - id: "upload-folder-to-gcs"
        if: ${{ steps.run-diff.outcome == success() && !cancelled() && steps.run-diff.outputs.CHANGES_DETECTED == 'TRUE' }}
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "${{ github.workspace }}/salesforce/output/"
          destination: "salesforce-sit-github-workflows/upload-object-changes/success_output"
          project_id: anz-x-gh-sf-dev-ef8edd
