# This workflow deploys changes to a Salesforce project to a Salesforce org with the check only flag
name: Verify

# This workflow will only run on Pull Reqeusts against master , develop and epic/*
on:
  pull_request:
    branches:
      - epic/*
      - "!epic/lock-card"
      - "!epic/disputes"
      - "!epic/fraud"
      - "!epic/anzx-bau"

jobs:
  prepare:
    runs-on: [self-hosted, salesforce]
    env:
      BASE_BRANCH: ${{ github.base_ref }}
    outputs:
      IS_SANDBOX_SECRET_SET: ${{ steps.checksecret.outputs.IS_SANDBOX_SECRET_SET }}
    steps:
      - name: Set Sandbox Name
        run: |
          if [ ${{ env.BASE_BRANCH }} == 'develop' ]; then echo SANDBOX_NAME=$(echo SYSTEST) >> $GITHUB_ENV; elif [ ${{ env.BASE_BRANCH }} == 'master' ]; then echo SANDBOX_NAME=$(echo STAGING) >> $GITHUB_ENV; else echo SANDBOX_NAME=$(echo ${{ env.BASE_BRANCH }} |  tr -d '-' | tr 'a-z' 'A-Z' | cut -d'/' -f 2 | cut -c1-10) >> $GITHUB_ENV; fi
      - name: Set secret prefix
        run: echo SANDBOX_SECRET=SALESFORCE_${{ env.SANDBOX_NAME }} >> $GITHUB_ENV
      - name: Check whether the sandbox secret exists
        id: checksecret
        env:
          MY_SECRET: ${{ secrets[env.SANDBOX_SECRET] }}
        run: |
          echo "IS_SANDBOX_SECRET_SET: ${{ env.MY_SECRET != '' }}"
          echo "::set-output name=IS_SANDBOX_SECRET_SET::${{ env.MY_SECRET != '' }}" 
          echo ${{ steps.checksecret.outputs.IS_SANDBOX_SECRET_SET }}

  build_and_deploy:
    # requires above step to execute
    needs: [prepare]
    runs-on: [self-hosted, salesforce]
    env:
      BASE_BRANCH: ${{ github.base_ref }}
      SFDX_NPM_REGISTRY: https://artifactory.gcp.anz/artifactory/api/npm/npmjs-org/
      SFDX_DISABLE_TELEMETRY: true
      SFDX_DISABLE_AUTOUPDATE: true
      HTTP_PROXY: http://127.0.0.1:3128
      HTTPS_PROXY: http://127.0.0.1:3128

    steps:
      - name: Set Sandbox Name
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        run: |
          if [ ${{ env.BASE_BRANCH }} == 'develop' ]; then echo SANDBOX_NAME=$(echo SYSTEST) >> $GITHUB_ENV; elif [ ${{ env.BASE_BRANCH }} == 'master' ]; then echo SANDBOX_NAME=$(echo STAGING) >> $GITHUB_ENV; else echo SANDBOX_NAME=$(echo ${{ env.BASE_BRANCH }} |  tr -d '-' | tr 'a-z' 'A-Z' | cut -d'/' -f 2 | cut -c1-10) >> $GITHUB_ENV; fi
      - name: Set secret prefix
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        run: echo SANDBOX_SECRET=SALESFORCE_${{ env.SANDBOX_NAME }} >> $GITHUB_ENV

      - uses: actions/checkout@v2
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Install npm packages"
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        run: |
          mv ci.npmrc .npmrc
          npm ci
      - name: "Authenticate the org"
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        shell: bash
        run: |
          echo 'Authenticating ${{ env.SANDBOX_NAME }}'
          echo ${{ secrets[env.SANDBOX_SECRET] }} > ./SFDX_URL_${{ env.SANDBOX_NAME }}.txt
          npx sfdx force:auth:sfdxurl:store -a ${{ env.SANDBOX_NAME }} --sfdxurlfile=./SFDX_URL_${{ env.SANDBOX_NAME }}.txt
      - name: "Generate package"
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        id: package
        shell: bash
        run: |
          git fetch --tags 
          ci/package.sh
      - uses: actions/upload-artifact@v1
        if: ${{ steps.package.outputs.ARTEFACT_GENERATED }}
        with:
          name: package
          path: ./artefact/

      - name: "Validate Package"
        if: needs.prepare.outputs.IS_SANDBOX_SECRET_SET == 'true'
        shell: bash
        run: ci/deploy.sh
        env:
          DEPLOY_ROOT: ./artefact/
          BUILD_COMMAND: validate
          ORG_NAME: ${{ env.SANDBOX_NAME }}
