# This workflow builds the webdriverIO tests with typescript
name: WebDriverIO

on:
  pull_request:
    branches: [develop]

jobs:
  typescript-build:
    runs-on: [self-hosted, salesforce]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Rename npmrc"
        run: mv ci.npmrc ./webdriverIO/.npmrc

      - name: "Install npm packages"
        working-directory: webdriverIO
        run: npm ci

      - name: "Enforce Style Guidelines"
        working-directory: webdriverIO
        shell: bash
        run: |
          echo "Checking WebdriverIO project files"
          npx prettier -c "./**/*.{ts,js}"

      - name: "Lint TypeScript files"
        working-directory: webdriverIO
        shell: bash
        run: |
          echo "Linting TypeScript files"
          npx eslint "./**/*.ts" -c "./.ts-eslintrc.json"

      - name: "Build Typescript"
        working-directory: webdriverIO
        run: npx tsc
