# This workflow builds the webdriverIO tests with typescript
name: Automation-Test-WebDriverIO

on:
  pull_request:
    paths:
      - "automation-test/**"
    branches:
      - develop
      - epic/anzx-bau

jobs:
  typescript-build:
    runs-on: [self-hosted, salesforce]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Rename npmrc"
        run: mv ci.npmrc ./automation-test/.npmrc

      - name: "Install npm packages"
        working-directory: automation-test
        run: npm ci

      - name: "Build UTAM"
        working-directory: automation-test
        shell: bash
        run: |
          echo "Building Page Objects"
          npx utam && npx prettier --write ./src/pageObjects

      - name: "Enforce Style Guidelines"
        working-directory: automation-test
        shell: bash
        run: |
          echo "Checking automation-test project files"
          npx prettier -c "./**/*.{ts,js,json}"

      - name: "Lint TypeScript files"
        working-directory: automation-test
        shell: bash
        run: |
          echo "Linting TypeScript files"
          npx eslint "./**/*.ts" -c "./.ts-eslintrc.json"

      - name: "Build Typescript"
        working-directory: automation-test
        run: npx tsc
